### ISSUE TITLE
Page and Block Types Reports

### ISSUE THREAD

**Issue by jhonatan-lopes** [mozilla/foundation.mozilla.org#10851]
Give admins the ability to generate reports for the CMS page types and their usage. This will be helpful in identifying which pages/page types are actively used and need more maintenance, as well as the latest changes in pages.

The goal is to provide editors/admins with analytics to understand which types of pages are most used, which in turn would help with CMS clean ups.

## Acceptance Criteria
* [ ] As an editor, I can see a Page Types report with:
  * [ ] Wagtail page type
  * [ ] Number of pages under that page type
  * [ ] Last page published under that page type
  * [ ] Last person that published a page under that page type
* [ ] As an editor, I can see a blocks report with:
  * [ ] Wagtail block type
  * [ ] Number of pages using that block
  * [ ] Types of pages that use that block
  * [ ] Last published page that used that block
* [ ] Regular users cannot access reporting features.
* [ ] Editors can choose to export these reports as spreadsheets 

## Tickets
* [x] #10853 
* [x] #10854
* [x] #10965 
* [x] #10966 
* [x] #10855
* [x] #11069 
* [x] #11070

┆Issue is synchronized with this [Jira Epic](https://mozilla-hub.atlassian.net/browse/TP1-173)

**Comment by simont-cr** [comment]
@jhonatan-lopes The epic itself had only 3 issues, all of them already completed. While the description includes two remaining tickets. Are these tickets still relevant for this epic or are those items that are no longer a priority?

**Comment by jhonatan-lopes** [comment]
@simont-cr, we still need to implement those at some point. The "block types usage" report is functional now but it would benefit from having filters and being able to export the reports to a spreadsheet

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

Kristina Shu Do you have context on the current status of this ticket?

**Comment by data-sync-user** [comment]
➤ Kristina Shu commented:

It seems accurate that https://mozilla-hub.atlassian.net/browse/TP1-189 ( https://mozilla-hub.atlassian.net/browse/TP1-189|smart-link )  and https://mozilla-hub.atlassian.net/browse/TP1-190 ( https://mozilla-hub.atlassian.net/browse/TP1-190|smart-link )  are still remaining but it would be good to check with Wagtail since I think this is a feature they we’re exploring. I would be ok with closing this.

**Comment by data-sync-user** [comment]
➤ Kevin Duong commented:

Simon Acosta Torres can we close this one?
