### ISSUE TITLE
[Fellowship Mini Site] Checklist of things that needs to be done (user experience POV)

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1132]
Here is a list of things that we could do to make the user experience of the site even better. I added a label on the side of each one so we know which ones are the most urgent issues. This is a master list, I'll create individual tickets to each one of them:

- [ ] 1. Once we have all the Pulse Profiles ready, we should link them to the names of each person in our[ Fellowship home page](https://foundation-mofostaging--pr-996.herokuapp.com/fellowships/) - **importance: high**
- [ ] 2. [Fellowship home page](https://foundation-mofostaging--pr-996.herokuapp.com/fellowships/) - section "Meet Some of the Mozilla Fellows". Make sure the copy there represents the Fellows the way we want (would we like emphasize what their fellowship focus are?). **importance: medium**
- [ ] 3. [Fellowship home page](https://foundation-mofostaging--pr-996.herokuapp.com/fellowships/) - section "Meet Some of the Mozilla Fellows" - Linet's Linkedin Profile link is not working. **importance: high**
- [ ] 4. [Fellowship home page](https://foundation-mofostaging--pr-996.herokuapp.com/fellowships/) - section "Applications are open" - to have a plan on what to do there (and when) once the applications close so users won't have the wrong expectations. **importance: high**
- [ ] 5. [Fellowship home page](https://foundation-mofostaging--pr-996.herokuapp.com/fellowships/) - section "Why Become a Fellow" - second bullet point - that link currently takes the users to [Featured Fellows](https://www.mozillapulse.org/featured) page, but it would make more sense if we apply a filter to see just fellows on Pulse. **importance: low**
- [ ] 6. [Directory](https://foundation-mofostaging--pr-996.herokuapp.com/fellowships/directory/) - team is currently working on that. Nice to have: pictures of Fellows (we are missing lots of past fellows' pictures) if possible. **importance: high**
- [ ] 7. [Directory](https://foundation-mofostaging--pr-996.herokuapp.com/fellowships/directory/) - we have a link for "Senior Fellows" but currently no area for them. UPDATE: Jesse asked to remove the placeholder "Senior fellows" for now. **importance: high**
- [ ] 8. [Support the Program](https://foundation-mofostaging--pr-996.herokuapp.com/fellowships/support/) - section "Host a Fellow" ("Learn more about how to get involved") - needs an updated copy. Connect with Ann Marie on that.**importance: high**
- [ ] 9. [Apply to be a Fellow](https://foundation-mofostaging--pr-996.herokuapp.com/fellowships/apply/). We need the Fluxx link as soon as the team has it so we can have a button that takes users to applications. This is very important since it is the only spot on the site that links users to applications!!! **importance: high**

**Comment by xmatthewx** [comment]
Thanks @taisdesouzalessa. Can you do me a favor? Let's set up a few GH Projects to organize and track these. Below are my proposed issue titles.

Final Launch Prep [project board]
 - 7 - Remove "senior fellows" as filter item in directory
 - 9 - Add link to Fluxx application
 - Please add any items in the [gdoc list](https://docs.google.com/document/d/1jaMBKfSOqrJ5I5XDGGq81D7sKvVM0FTBk67NQuv1O8k/edit) and link top of that doc to your new project

Post-launch [project board]
 - 4 - Draft and plan "Application closed content" 
 - 1 - ~~Link featured fellow names to pulse profile~~ "Pull profiles via Pulse api for featured fellows"
 - These two issues should only block launch if Amy & Jesse think so. Neither feel critical to me. 
    - 2 - Update "Meet Some fellow" content
    - 8 - "Host a Fellow" content update

Won't fix
 - 5 - Link to Fellow projects on pulse - a filter would be significant to build. And, I don't see a strong reason to hide other work by the network. The directory will give easy access to a fellow's specific work. 

Other
 - 3 - Fix Linet's linkedin link - Can you comment in spreadsheet and assign to Ann Marie to fix? No need to file. 
 - 6 - Fellow profile photos - Team is on this. We won't block launch or sharing. No need to file.

**Comment by taisdesouzalessa** [comment]
@xmatthewx thanks for your guidance here :).

1. Project Board[ is here](https://github.com/mozilla/foundation.mozilla.org/projects/11) Feel free to move the cards around and assign to the right people.
2. "Pull profiles via Pulse api for featured fellows" - I think this is a different issue than the one I was referring to. I created a ticket for the one I mentioned (#1136). I can also create one for pulling profiles if you want, just let me know.
3. I didn't do this item "Please add any items in the gdoc list and link top of that doc to your new project" because I am not sure where I should add the board link. Could you clarify that a bit further?

**Comment by xmatthewx** [comment]
2. those featured people are built static now, but should eventually be pulled via the api. that way we can change who is featured easily and just use their profile content. 

3. i just meant we can retire that doc when everything is in the boards. was suggesting we put a link at top of the doc to the launch project board. make sense?

**Comment by taisdesouzalessa** [comment]
> those featured people are built static now, but should eventually be pulled via the api. that way we can change who is featured easily and just use their profile content.
Ok - I will create a ticket for it

> 
i just meant we can retire that doc when everything is in the boards. was suggesting we put a link at top of the doc to the launch project board. make sense?
I'll add the link to the project board on top of that doc then.

**Comment by taisdesouzalessa** [comment]
Board was created here: https://github.com/mozilla/foundation.mozilla.org/projects/11

Issues addressed. Thanks @xmatthewx for all your support here!! Teamwork :)

Closing this ticket.
