### ISSUE TITLE
[Wagtail Component] Figure, Image, Image text, Figure Grid - MASTER implementation ticket

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1516]
Implementation ticket from discussion that happened here: #1438

[Here are all image components in the same comp](https://mozilla.invisionapp.com/share/32IAJFURME8#/296012268_All_Image_Components_in_1_page)
[Doc here](https://docs.google.com/document/d/1nsu6k-MdJ1yL9myRgVg8im6Uc0wH_RwSa52Ul4yFfyo/edit?usp=sharing) 

**Individual tickets:**

- [x] [Wagtail Component] Video Component Updates #1511
- [x] [Wagtail Component] iFrame Component Updates #1512
- [x] [Wagtail Component] Large Image (Full width) #1513
- [x] [Wagtail Component] Image + Text #1514
- [x] [Wagtail Component] Figure Grid Component Update #1515 

cc: @kristinashu @gvn
