### ISSUE TITLE
Auto crop all cms images

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2426]
Design done in #2402 

Any image uploaded to the cms should be automatically cropped.

### Home
- [x] hero image (desktop & mobile - 16:9 ratio)
- [ ] featured news image (desktop & mobile - 16:9 ratio)
- [ ] both happening now sections (card desktop & mobile, and wide version - 16:9 ratio) 

### Initiatives
- [ ] feature program (desktop & mobile - 16:9 ratio) 

### Participate
- [ ] hero image - WIP (pending header template) #2275
- [ ] small feature cards - 16:9 ratio
- [ ] larger features - 16:9 ratio

### Future
- [x] make sure we do this for upcoming Fellowship #2282 (probably 1:1 ratio)
- [ ] make sure we do this for upcoming Blog pages #2281 
- [ ] design fallback images for cms images #2416 then implement them

cc @beccaklam @alanmoo

**Comment by alanmoo** [comment]
The phrasing of this throws me off; Do you mean that when images are shown in those various parts of the site, the output should automatically render them at specific sizes?

I ask to clarify because when uploading images to the site, they're dumped into one main bucket of content and I don't believe we should do any sort of automatic cropping at that point because the image could be used in a variety of ways in the future.

**Comment by kristinashu** [comment]
Right, I mean that users see a cropped image but I guess the image isn't truly being cropped.

The purpose is to avoid things like this where content is misaligned because one image is bigger than another:

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/1068783/50925680-e624aa80-1407-11e9-94e1-a276361fac70.png">

**Comment by alanmoo** [comment]
Got it. @youriwims This may be a good one for you to take on, as it is somewhat aligned with your other work on the hero image.

**Comment by alanmoo** [comment]
@Pomax I think the use of nested python classes and templates makes us unable to use the nifty cropping that Wagtail offers us. Can you take a look into this so we can brainstorm what kind of solution is the proper one for it? Happy to hop into a call once you've gotten your head around this thread.

**Comment by cadecairos** [comment]
Closing this issue due to its age, if this is work that we still want to do, please refile this with up to date information so that it can be put in the correct milestone with up to date estimates.
