### ISSUE TITLE
Buyers Guide Updates for V-day ❤️

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2438]
Master ticket for the small website updates and marketing for our Valentines Day push of the guide. 

[Notes](https://docs.google.com/document/d/1FLTdpgUO0XY3nHyqdPA1XxtqES9UIzZ683bQFgh_1Ck/edit?usp=sharing) from kick-off with @caltrider.

### 🚀  Launch Feb 6 
(take down March 1st - category and hero banner)

### Content & Marketing
Jan 14: Product list finalized - [content doc](https://docs.google.com/spreadsheets/d/1hm7LliaSu3ypNFlp5oj8CKTRu4Q46nbjTBw-nXR3oDE/edit?usp=sharing)
Jan 28: Research ready for final review
Feb 4: All research is ready for input into CMS
Feb 6: Media Launch
Feb 11: Email to list

### Design
- [x] New V-Day themed homepage #2444
- [x] Source and crop images for new products #2445
- [x] Social images https://github.com/MozillaFoundation/Design/issues/321
- [x] Add content to cms in draft mode - [content doc](https://docs.google.com/spreadsheets/d/1hm7LliaSu3ypNFlp5oj8CKTRu4Q46nbjTBw-nXR3oDE/edit?usp=sharing) #2559
- [x] Pre populate with some votes

### Engineering (Alan to triage later)
- [x] Add Draft mode functionality #2434 (Pomax)
- [x] Add new category tab #2482 
- [x] Replace banner graphic #2464
- [x] Update homepage copy #2500
- [x] Give Rebecca R access to cms
- [x] Add NSFW treatment #2518

cc @alanmoo @beccaklam @natalieworth @Pomax @xmatthewx @gideonthomas
