### ISSUE TITLE
Misinfo Master Ticket

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#2755]
### Feb 11

- [x] Open Letter (https://github.com/MozillaFoundation/Design/issues/324)

- [x] Mozilla Campaign Page (Introductory paragraph, open letter, petition snippet)
- [x] Campaign graphic (#2545)
- [x] URL (for the Campaign Page?)
- We went with a traditional url: https://foundation.mozilla.org/en/campaigns/eu-misinformation/ with a shortlink to direct to it: [mzl.la/fbopenletter](https://mzl.la/fbopenletter)

### March 11

- Special Landing Page Template #2542 (discusses this work)

- [x] Phase 1 (Bannered Template) #2725 _In progress_

- [ ] Phase 2 (Editorial Banner) #2756

- [x] Scorecard  #2643 _In progress_

- [x] Resources for partners (https://github.com/MozillaFoundation/Design/issues/326) _In progress_

_Nice to have_

- [ ] Accordion Component https://github.com/mozilla/foundation.mozilla.org/issues/2695 for Scorecard Methodology page

**No design support needed for these deliverables:**

- Tools (election bundle) _(MoCo is creating this)_

- Mitchel op-ed

**Comment by beccaklam** [comment]
This work is paused indefinitely. Some things like the Phase 1 Bannered Template and the Resource Template will still be moved going forward. But the Scorecard will not be moving forward due to the Campaigns team not being able to move forward with that work.
