### ISSUE TITLE
Blog epic

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2797]
### Goal
- Use Foundation site as the primary destination for announcements etc to drive traffic to the site
- A place where we can start to tell deeper/richer stories about fellows, awardees, and the people in our network

### Links
Comps https://redpen.io/p/bha12cf7387de4f7e7
Deck https://docs.google.com/presentation/d/1NWfOotxMRcfE78CehF2uqZefEWEUm5siwrgOXzmbM_8/edit#slide=id.p

### Stage 1: Posting strategy
 - [x] Blog pros and cons [doc](https://docs.google.com/document/d/1oiO0LB_ej4FxhpbCbjdATd2hSjwTimdVF284kVNR5dc/edit#heading=h.py9jj56uzob)
- [x] Decide on name (aka url): `Blog` ~~vs Stories vs Articles~~
- [x] Consult with Kevin, Sydette, Jen, Mark, someone from IH team, someone from MozFest team, moco, and anyone else who currently posts blogs
- [x] Decide how we integrate with existing blogs: will we continue to also post to Medium and MoCo's blog [(doc)](https://docs.google.com/document/d/1FvzDd8zPL_rk3rRMzPaieZJEd7e5YmJrnNt4LtwAeec/edit)
- [x] Once build: onboard comms team and make sure they always link to our blog over Medium and MoCo's
- [ ] Document tutorial and hold a working session to onboard staff

### Stage 2: Blog post detail page 
- [x] Design https://github.com/mozilla/foundation.mozilla.org/issues/2911
- [x] Dev MVP https://github.com/mozilla/foundation.mozilla.org/issues/3029 
- [x] Dev share button https://github.com/mozilla/foundation.mozilla.org/issues/3157
- [x] Dev Related Posts https://github.com/mozilla/foundation.mozilla.org/issues/3162

### Stage 3: Blog overview pages
- [x] Design overview page, if someone clicks on a tag or authors #3165
- [x] Dev overview page for /blog #3370
- [x] Dev tag page for /blog?tag=[name] #3371
- [ ] Add to main nav (only later once we have content)
- [x] Explore adding RSS feed #3588

### Stage 4: Category pages
- [x] Dev: add categories to post page #3560
- [x] Dev: create category landing page #3562
- [x] Dev: update /blog tags to categories #3563 

### Stage 5: Integrate onto site 
- [x] Exploratory comps https://github.com/mozilla/foundation.mozilla.org/issues/3434
- [x] Narrow down features and next steps based on stakeholder convos
- [x] Dev: create wagtail component #3564
- [x] Design: add feed to homepage #3581
- [x] Dev: add feed to homepage #3611

### Stage 6: Post MVP blog detail page features
- [x] Dev: add optional comment component #3589
- [ ] Design: link to author

### Examples of content
- https://medium.com/read-write-participate
- https://medium.com/mozilla-festival
- https://medium.com/@mozilla
- https://blog.mozilla.org/netpolicy/
- https://marksurman.commons.ca/blog/ 
- https://internethealthreport.org/your-ideas-for-the-2019-internet-health-report/ 
- https://foundation.mozilla.org/en/campaigns/aadhaar/blogs-and-press/ 
- also research blog, science blog

cc @alanmoo @xmatthewx
