### ISSUE TITLE
Mozfest: Add GA event tracking if useful

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#3255]
## TODO

Attach GA events mentioned in [this spreadsheet](https://docs.google.com/spreadsheets/d/1x-CP_HYaAs3oRv2cjbSFu8w5Z938E4cyHQ3hvh17c6c/edit#gid=2085475948).

## Initial conversation

If useful, let's add GA events to mozfest site. 

 - [x] identify useful things (e.g. ticket button, submission button)
 - [ ] prep category, action, label to align with other properties
 - [ ] wire it up

@gideonthomas - you've been volunteered by others as best person for step 1. I can take on step 2.

**Comment by gideonthomas** [comment]
here's a list of what is useful to track in order of priority so it's not an issue if we can't get to it all (@xmatthewx can you map them to GA events?):
1. Submit proposal button clicks
2. Watch video clicks
3. Ticket button clicks
4. Regular page views for all pages (assuming we already have that wired up)
5. If it needs to be enabled, Behavior flows (user journey)
6. Button clicks on this page: https://mozillafestival.mofoprod.net/en/proposals/
7. Churn rate (I think it automatically does this?)
8. Referrals to pulse (via the news section and the wrangler profile section...we need a way to differentiate this which I don't think you can do on pulse directly).
9. Social clicks in the footer

I'll chat with Marc tomorrow and and find out if anything else needs to be added.

**Comment by xmatthewx** [comment]
Great. I've mapped 4 events in this [spreadsheet](https://docs.google.com/spreadsheets/d/1x-CP_HYaAs3oRv2cjbSFu8w5Z938E4cyHQ3hvh17c6c/edit#gid=2085475948). Let me know if any phrasing or variables are confusing. 

We'll get page views, flows, referrals, bounce, etc by default. Links to Pulse will show up in Pulse analytics and tell us the mozfest page that made the referal. I did add profile card social links, which wouldn't be visible to us anywhere otherwise. 

@gideonthomas - can you assign this for implementation? Or close this and open a new ticket?

**Comment by gideonthomas** [comment]
Awesome! Thanks Matthew, I'll update tomorrow.

**Comment by gideonthomas** [comment]
whoever takes this on -- can you use [this spreadsheet](https://docs.google.com/spreadsheets/d/1x-CP_HYaAs3oRv2cjbSFu8w5Z938E4cyHQ3hvh17c6c/edit#gid=2085475948) to send GA events?

**Comment by alanmoo** [comment]
@mmmavis to chip away at this at the end of the July 19 sprint
