### ISSUE TITLE
Update PNI product page styling

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#3732]
master issue: #3716

Comps: https://redpen.io/p/aj7f2e09f704b2e4ee

# Styling changes:

## **Remove**
- [ ] Remove fields listed [here](https://docs.google.com/spreadsheets/d/1tcFlDgrxxo4Mj5QP-pCFyB4QSCuPMi5vumLQu_r5-QI/edit#gid=0)
- [ ] Remove all accordions except for new accordion for Minimum Security Standards
- [ ] Remove pink info button and 'Read our research first' jump link in the "Tell us what you think" creep-o-meter box
- [ ] Remove the title "Our Research" and the pink info button and "How to use this guide" jump link
- [ ] Remove icons for old "Can it spy on me"/"It uses" section
- [ ] Remove icons for "How to contact company" section
- [ ] Remove smiley faces (not the creep-o-meter) and red highlights

_Comp:_
![remove](https://user-images.githubusercontent.com/20977376/66508104-6b73e300-ea9e-11e9-9412-e88bd979fcaa.jpg)

## **Add**
- [ ] Add new fields listed [here](https://docs.google.com/spreadsheets/d/1tcFlDgrxxo4Mj5QP-pCFyB4QSCuPMi5vumLQu_r5-QI/edit#gid=0)
- [ ] Add Review Date
- [ ] Add Minimum Security Standards section with stars
_Comp:_
![Screen Shot 2019-10-09 at 2 16 22 PM](https://user-images.githubusercontent.com/20977376/66508571-65323680-ea9f-11e9-8509-a7264d3f3ab1.png)
- [ ] Bold field titles and corresponding answers
_Comp:_
![Screen Shot 2019-10-09 at 2 16 56 PM](https://user-images.githubusercontent.com/20977376/66508648-86932280-ea9f-11e9-983a-1ab177a5a77b.png)

- [ ] Only show "Can it spy on me"/"It uses" items if the answer is Yes or Unknown _(might be done in https://github.com/mozilla/foundation.mozilla.org/issues/3733)_
- [ ] Hide "Parental controls?" if answer is N/A (might be done in #3733)
- [ ] Hide "Collects biometric data?" if answer is N/A (might be done in #3733)
- [ ] Add new styling to "What could happen if something goes wrong" section
    - [ ] Contain section in a div with a gradient border
    - [ ] Creep-o-meter face should break out of the border with about 16px of spacing on its left and right side
    - [ ] Center align the copy inside the div
     _Comp:_
![Screen Shot 2019-10-09 at 2 17 43 PM](https://user-images.githubusercontent.com/20977376/66508686-990d5c00-ea9f-11e9-91a7-9c9ad9a9a850.png)

- [ ] "How to contact the company" should be body.normal instead of H3 to downplay the section
_Comp:_
![Screen Shot 2019-10-09 at 2 18 23 PM](https://user-images.githubusercontent.com/20977376/66508728-ac202c00-ea9f-11e9-8796-dbdfb54d4507.png)

- [ ] Update copy to match comps

**Comment by Pomax** [comment]
@beccaklam this is still a little rough and easier to describe as a detailed changelist that can be run through when the design is finalised.

**Comment by kristinashu** [comment]
Rebecca has update the check-list in the first comment. Happy to have a quick zoom call to review the changes as well if needed.

**Comment by Pomax** [comment]
Closing as complete, with the following followup issues:
- https://github.com/mozilla/foundation.mozilla.org/issues/3793
- https://github.com/mozilla/foundation.mozilla.org/issues/3794
