### ISSUE TITLE
[Header/body newsletter list conflicts] Epic

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#3924]
### Background:
Discussion started in #3848. The proposed and accepted solution [is in this doc](https://docs.google.com/presentation/d/1VnhbLJ6gFYiF9E-6qe4ToUXDcmR1XCS7Kzvj8TCH1pY/edit?usp=sharing)

### Master ticket
- [x] 1. Hide the “newsletter” top button in pages that have form in their body #3925
- [x] 2. Make copy more clear inside the form from body  #3926
- [x] 3. Make copy more clear in footer #3927
- [x] 4. Thank you page: add paragraph giving people the option to manage their newsletter subscriptions #3928

### Deadline
January 2020

Assigning: @alanmoo  and @kristinashu for triage and awareness

cc: @mmmavis @caltrider

**Comment by kristinashu** [comment]
Here are a few examples of other sites that have multiple newsletter signups. Not necessarily good ones, but still interesting to see how others are handling it.
http://nymag.com/newsletters/
https://www.theguardian.com/email-newsletters
https://www.cbc.ca/news

**Comment by taisdesouzalessa** [comment]
Thanks for the benchmarks, Kristina. I was having a hard time finding examples. I will add those flows to a slide for reference to us.

**Comment by taisdesouzalessa** [comment]
Closing this epic as all design tickets were closed and implementation tickets were created.
