### ISSUE TITLE
PNI product page: misc updates

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4017]
Based on updates in #3904 and user testing results in #4013. Let's decide review the misc small updates and decide if we want to proceed with implementation. 

### Our research is too low on the page and users want that information
_(Note: changing creep-o-meter position may negate the following ...)_
- [ ] Can we reduce height of the product image
- ~Can we shorten the product blurbs? (keep in mind for next year, but won't do anything this year)~ _for Jen to consider next year_

### Users are not hitting the submit button on the creep-o-meter
_(Will consider next year)_
- [ ] Retest in usertesting.com to see if bug is reproducible and not just a result of the busy environment of MozFest
- [ ] Should submission be automatic after user has clicked all necessary buttons?

### Newsletter ask after voting is annoying
- [x] Change frequency of prompt https://github.com/mozilla/foundation.mozilla.org/issues/3943
- [x] Add close X #3996
- ~Could email interstitial copy and opacity: Users are stopping at PNI's email interstitial and not clicking through to see results. We're hoping that changing the copy (to allude to the results on the next page) and lowering the opacity of the interstitial background will help fix this problem. [Copy from Jen](https://docs.google.com/document/d/1MhA6TSJ-Gg8FW6q5y5hhTJ_UsfnV0T6ablZwhkwG0Vg/edit#)~

### Add labels to Recommended products
- [x] A senior emailed Jen and kindly asked for labels to be added to the Recommended products images as _"Seniors (and others ?) may not always connect with a picture as being this or that or A,  B,  C or D."_ https://github.com/mozilla/foundation.mozilla.org/issues/4022

### Accessibility
- [ ] Update colour of body-small text and H6 https://github.com/MozillaFoundation/Design/issues/422 _(will look at as part of brand work)_

**Comment by kristinashu** [comment]
@beccaklam I think you could open a design ticket for "Can we reduce height of the product image" and then we could probably close this ticket.

**Comment by beccaklam** [comment]
Most of this work is in progress, other work has been tabled for next year. The only outstanding design item (height of images) is covered in this ticket:  #4056.
