### ISSUE TITLE
IA: audit current site

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4110]
Based on planning in https://github.com/mozilla/foundation.mozilla.org/issues/4090 and [our working doc](https://docs.google.com/document/d/1Co1uocNdhnxmYNBSR9QAg4BQYckTsFYhr1I6vWSCFhY/edit?usp=sharing).

### Todo
- [x] Complete a quick, [high level content analysis](https://docs.google.com/document/d/1Ez5ku0X00osfY4IyrHdORCofXaVQvZdqo_tjznQ8PFo/edit?usp=sharing)
- [x] Complete a [structural audit](https://docs.google.com/spreadsheets/d/1EbkHuEVsIZRt-omYW47Z0iP569K6NRG1zgcYGoxt1ME/edit?usp=sharing)
- [x] Create a sitemap for our current site, include a high level view of content on these pages ([high-level](https://mozilla.invisionapp.com/freehand/document/r94Tsrd1H) & [more detailed](https://mozilla.invisionapp.com/freehand/document/cD5Bj67vm))
- [x] Make sure the format is shareable and digestible
- [x] Make sure it will be easy to edit and keep up to date in the future
- [ ] Review diagram with the engagement team

cc @taisdesouzalessa

**Comment by kristinashu** [comment]
I think this is considered done! All the links are above. It has been shared with designers, Anil, Alan, and we will continue to share it as we get the analytics.

@beccaklam please close or add anything else you can think of!
