### ISSUE TITLE
Venmo: story collection

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4116]
[Advocacy strategy doc](https://docs.google.com/document/d/1TctYFZhKlvKfLwVu8LygmcdBhK156cJISPXReLXDFWo/edit).

### Project prep
- [x] @kaili09 to update the [original stakeholder interview doc](https://docs.google.com/document/d/18JdXFbhJQuvbwKbK-O6EHefg-n7-s3s0r6IgrpUwJ5E/edit) to reflect the new mood and tone of the campaign

### Phase 1: Story collection
Deadline: Wed Jan 22
- [x] Advocacy and design to decide if we should embed a form on our site or just link to a google form
- [x] Advocacy to provide [email copy](https://docs.google.com/document/d/1i_O6eMmr1wT0Tjo6KMP1T7JdQbSuwnG8FEhSOgUH6AA/edit) _(approved)_
- [x] Advocacy, Jen and design to decide on campaign title
- [x] Advocacy to set up [form](https://docs.google.com/forms/d/e/1FAIpQLSdiIU592_ULPkM_Ri21arxudE1t9qkc12WHNjhMwHABemNyVw/viewform)
- [x] Nat to determine creative direction that will work for email, social, landing page, and ads 
- [x] Nat to make sure branding will work for story share out site as well
- [x] Nat to create email graphic
- [x] Nat to create social graphics
- [x] Nat to create form graphic

### Phase 2: Story share out
- Deadline after All-Hand (need exact deadline)
- Ticket https://github.com/mozilla/foundation.mozilla.org/issues/4117

### Phase 3: Ads
- TBD

#### Other links
- old email petition [email doc](https://docs.google.com/document/d/1qqNd9Pq-FGl2UyUe5hJDfIwKt6auT66PCPGslVn6NbI/edit)
- old ticket design https://github.com/MozillaFoundation/Design/issues/406

cc @beccaklam

**Comment by kristinashu** [comment]
### Options for story collection
Criteria: anonymous, easy for users to use, easy for multiple staff to see and sort

#### 1) Google form similar to [YouTube Regrets](https://docs.google.com/forms/d/e/1FAIpQLSffrG1EK1V5MYqujMp10f-H_NwIuV7znIMr0oFk6dUb1gO1Ig/viewform)
- Pro: easy to set up, easy for users to use
- Con: doesn't drive traffic to our site

#### 2) Embed a form on our site
- Pro: brings users to our site
- Con: tested embedding a Google Form and an AirTable form [here](https://foundation.mofostaging.net/en/campaigns/test-form/). User experience for this is terrible.

#### 3) Use our Saleforce form similar to [petition comments](https://foundation.mozilla.org/en/campaigns/tell-amazon-require-two-factor-authentication-all-ring-accounts/)
- Pro: easy to set up, easy for users to use, and brings users to our site
- Cons: Salesfoces' character is too low for this story submission use case

#### Recommendation
We go with option 1 (link to a Google form) but include a link to our site in the intro text. The majority of users will be coming via our email list so getting them onto our site isn't critical.

**Comment by alanmoo** [comment]
I’m tapping out of having an opinion here, but flexible form collection seems to be something we should seriously consider adding to the site capabilities sooner rather than later. @gideonthomas this might be the kind of thing you could help guide in a practical way.

**Comment by gideonthomas** [comment]
I think Kristina's recommendation is right for this -- Google forms or survey monkey is probably the most pragmatic solution since our main marketing channel is email.

filed a ticket for discussing long-term solutions (https://github.com/mozilla/foundation.mozilla.org/issues/4128)

**Comment by kristinashu** [comment]
@natalieworth I've added the email copy from Kaili to the first comment ^

**Comment by natalieworth** [comment]
Have 2 directions [started in here](https://redpen.io/p/dx23cb219d8a457144)
The landing page is rough, but I wanted to show how the image directions would work on the site.

**Comment by natalieworth** [comment]
Hey @kaili09 , I have email graphic here: https://redpen.io/ks78aaed0d1af75d03
Let me know if you have any feedback :)

**Comment by natalieworth** [comment]
@kaili90 Final email graphic is in here: https://drive.google.com/drive/folders/14_VRTOUbYPaKFTebVBZGPS6izN1I9I8V?usp=sharing

**Comment by natalieworth** [comment]
and final form graphic is here https://drive.google.com/drive/folders/1f7LePdE4xgbLvQfw9W3OiHbXAlEXto7x?usp=sharing

cc @kaili90

**Comment by kristinashu** [comment]
Looks soooo good Nat!

Do we need a graphic for social (Twitter and Instagram)? Maybe with the mozilla logo and a short link over top of the graphic?

**Comment by natalieworth** [comment]
Sent final social file (we only need Twitter option for now) to Audrey for the social story collection ask. File is here for reference: https://redpen.io/ebf823371fc783c432

**Comment by natalieworth** [comment]
@kristinashu Is this okay to close/ I can open new tickets if we end up needing more graphics or a final site design.

**Comment by kristinashu** [comment]
Yes! Good to close. There's a ticket for the site design here #4117.

**Comment by natalieworth** [comment]
@Audreymofo Final file for this is here too ([in the drive](https://drive.google.com/open?id=1b-leSFduqH_vr7ssNh042pat4mgOVu4s)) :)
