### ISSUE TITLE
Venmo: story shareout

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4117]
[Advocacy strategy doc](https://docs.google.com/document/d/1TctYFZhKlvKfLwVu8LygmcdBhK156cJISPXReLXDFWo/edit) and [email doc](https://docs.google.com/document/d/1qqNd9Pq-FGl2UyUe5hJDfIwKt6auT66PCPGslVn6NbI/edit).

### Phase 1: Story collection
- Ticket https://github.com/mozilla/foundation.mozilla.org/issues/4116

### Phase 2: Story share out
Deadline after All-Hand (need exact deadline)
- [ ] Advocacy to provide selected stories
- [ ] Advocacy to provide intro copy
- [ ] Design to create simple wireframes for story share out site
- [ ] Design to create banner graphic (possibly a looping video background)
- [ ] Design to create a few images for the selected stories
- [ ] Design to create social graphics

### Phase 3: Ads
- TBD

cc @natalieworth @beccaklam @kaili09

**Comment by kristinashu** [comment]
This is on hold until we get more high quality story submissions.

**Comment by kristinashu** [comment]
I don't think this is gonna happen so closing :)
