### ISSUE TITLE
Reduce number of template options under campaigns

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4221]
Based on discussion in https://github.com/mozilla/foundation.mozilla.org/issues/4064

There are so many options and I don't even know what they all do so staff won't know either, please remove what we can.

### Todo
- [ ] @Pomax @mmmavis @xmatthewx to discuss before moving forward on this but in the meantime, please comment here if you have any thoughts/concerns. 
- [ ] Make sure tempaltes with `remove` aren't currently in use anywhere
- [ ] Remove templates with `remove` next to them

### List of templates currently available under campaigns
(Alan's description of [the page types](https://docs.google.com/document/d/1ZZtmOTxVMclvwULrG2IJKwO3P7tHCjk2jZb9LVIFZrg/edit))

- Bannered campaign page (keep)
- Blog page (keep for now)
- Campaign page (keep)
- Homepage (remove?)
- Index page (remove?)
- Mini site name space (remove?)
- Modular page (remove?)
- Mozfest homepage (remove?)
- Mozfest primary page (remove?)
- Opportunity page (keep)
- Primary page (remove?)
- Redirecting page (keep)
- Youtube regrets page  (keep)

### Screen cap from prod
<img width="492" alt="Screen Shot 2020-01-06 at 2 07 52 PM" src="https://user-images.githubusercontent.com/1068783/71853683-0164dd00-3091-11ea-854d-cac8f93918ce.png">

**Comment by Pomax** [comment]
I'm 100% in favour of removing the modular/mini pages, but we initially made almost everything inherit from those two types, so while entirely doable and desirable, it's worth bearing in mind that this will be a large lift requiring quite a bit of care to make sure we don't break things along the way. (I think they still stem from that workweek in Vancouver where we did our very first wagtail work together =D)

**Comment by kristinashu** [comment]
> I see the mozfest page types are marked for removal too - mozfest is currently its own "app" with its own page types because it had different nav and content requirements compared to the foundation site. Are we redoing those pages in terms of page types we're keeping?

This list is only for pages created under `campaigns`. So I assumed mozfest ones would be ok to remove from there but still keep then for the mozfest instant. 

> I'm 100% in favour of removing the modular/mini pages, but we initially made almost everything inherit from those two types, so while entirely doable and desirable, it's worth bearing in mind that this will be a large lift requiring quite a bit of care to make sure we don't break things along the way. (I think they still stem from that workweek in Vancouver where we did our very first wagtail work together =D)

Are you saying we could remove modular/mini pages completely? 

I feel a spreadsheet coming on... maybe this ticket should be for reviewing all the options under all the different "Page created under X"? If so then I can start on a spreadsheet.

**Comment by Pomax** [comment]
Ahhh, I see, I thought this issue was about removing the underlying models and templates, rather than curating the list of visible page types! In that case please disregard my previous comments. Instead, this looks like a good slimming down.

**Comment by Pomax** [comment]
Looking at the current data organisation, one thing to note is that `/campaigns` is an IndexPage, and so anything we change in terms of page types allowed under that will also affect all other IndexPage instances (which, as far as I can see right now, is the Blog page).

So one thing to consider is that https://github.com/mozilla/foundation.mozilla.org/issues/4232 should make this work easier by virtue of "tailoring" index pages to the content under them.

I'll mark this issue as "blocked" by 4232 for now, and then we can more efficiently weed that list when the index page work has completed.

**Comment by kristinashu** [comment]
Note: Kaili has said "I've been confused in the past about why the blog option existed under campaigns so good to know it'll be disappearing"
