### ISSUE TITLE
MozFest site: updates - due March 5

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4242]
The MozFest site design updates have been finalized in #4243. Let's chat after stand on Monday.

### Todos
- [x] Video background with text and button https://github.com/mozilla/foundation.mozilla.org/issues/4264
- [x] Make sure no content crosses over to the snippet (i.e., snippet should take up the entire side column) #4271
- [x] Make the nav CTA button an optional field #4249
- [x] Make signup sticky on mobile #4270
- [x] Remove Twitter and Location section #4267
- [x] Remove Medium link from the footer #4267
- [ ] Make all text is localizable #4257 (check with Théo to see if there's anything else)
- [x] Update Percy tests to match the new homepage #4265

cc @beccaklam

**Comment by mmmavis** [comment]
@kristinashu do you know if this can go live before the actual public announcement?

**Comment by kristinashu** [comment]
I think the dev work (like adding the video background) can launch before the announcement and then Marc can update the content in the CMS just before the announcement.

**Comment by mmmavis** [comment]
@kristinashu sounds good!

**Comment by mmmavis** [comment]
@TheoChevalier I've just landed the fix for #4257. Can you let us know if there's any other i10n related work we have to tackle?

**Comment by TheoChevalier** [comment]
> @TheoChevalier I've just landed the fix for #4257. Can you let us know if there's any other i10n related work we have to tackle?

Awesome, thanks Mavis! I just found out an issue with the language switcher, which also affects the MozFest website (filed https://github.com/mozilla/foundation.mozilla.org/issues/4290). But appart from that, I think we’re covered

**Comment by kristinashu** [comment]
Still some follow up tickets but the bulk of the work is done and it is awesome. I can't wait for the world to see it next week!
