### ISSUE TITLE
IA: shareout of the report to all staff

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4302]
Follow up from #4302 

### Todo
- [x] Draft email for all staff (edit made by Taís)
- [x] Finalize slide deck (overview deck that links to interview deck)
- [x] Email or slack all staff the report - [check this checklist](https://docs.google.com/document/d/1Bm2F7anspI3Nshgg67tZYVnVeFdIqk1Ye2XRcZldzjk/edit?usp=sharing) first
- [x] Set up a meeting to walk through the report for any interested staff
- [x] Prep for meeting

**Comment by taisdesouzalessa** [comment]
@kristinashu do we want to share only this report to staff or are we sharing all the work we did so far related to IA? If both, I will compress the presentation otherwise it will be too much. Also, the email draft will look different depending on how much we are sharing.

**Comment by taisdesouzalessa** [comment]
[Draft ready here](https://docs.google.com/document/d/1Bm2F7anspI3Nshgg67tZYVnVeFdIqk1Ye2XRcZldzjk/edit?usp=sharing) - open for feedback: @kristinashu @sabrinang @beccaklam feel free to edit it. Once we have a more refined version I'll share with Matthew and Anil for final revision.

**Comment by beccaklam** [comment]
The email draft looks good to me @taisdesouzalessa !

**Comment by kristinashu** [comment]
Yay! Shared in mofo-staff channel. Meeting is set for Wed Apr 15 at 9am PT. 

Next step: Becca and Tais to prep for the presentation.

**Comment by taisdesouzalessa** [comment]
[Presentation Plan here](https://docs.google.com/document/d/1rxkSGVMFwKr9xDvVqGg6VvwbcIIXIain0MEs1oEh_MI/edit?usp=sharing). @beccaklam please add your estimated duration to the table and I can use the remaining time for the Internal Stakeholders Interviews Report. I'll trim my presentation based on how much time I'll have, covering only some of the main highlights. 
We can also rehearse it tomorrow if you want.
Thanks!

**Comment by kristinashu** [comment]
This is excellent, thank for organizing this so nicely! 

@taisdesouzalessa how about you send out the little slack reminder tomorrow in the mofo-staff channel to encourage more people to come and let them know of the updated time.
