### ISSUE TITLE
OLE content review

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4355]
We need to audit OLE work and decide what should be archived, what should live on the MozFest site, and what should live on the Foundation site and where.

Kick-off [meeting notes](https://docs.google.com/document/d/1qBHbGlPp8y7mLfBexH4wKNLmeusIo4d_CcN7HyI-LXY/edit#) and [interview doc](https://docs.google.com/document/d/1OQ02Vu988lceL2j-DuKGqTKeM04OYRxM6NqKVq5iEdI/edit?usp=sharing).

### Todo
- [x] @stephwright & Kristina G will compile a list of all our Open Leadership touch points (e.g. pages on the foundation site, blogs, email list, pulse, social, wiki...)
- [x] @stephwright & Kristina G to add comments to this list, everything should be either: 
  - archived
  - moved to MozFest site
  - consolidated on Foundation site 
- [x] Review this list with the rest of the mozfest team and engagement team
- [x] @stephwright & Kristina G to write/compile content that will appear on MozFest site and Foundation site
- [x] Designers to advice on where the content should live
- [ ] @stephwright & Kristina G to create the pages
- [ ] Engineers to create relevant url redirects and any other archiving work that comes out of this

**Comment by stephwright** [comment]
This is fantastic @kristinashu ... thanks for pulling together!  I'll share w/ KG during our mtg this week (Thurs) & update as necessary!

**Comment by stephwright** [comment]
Hi @kristinashu ... KG and I have reviewed all the OLE content and talked to Marc (responsible for the MF site) and have made decisions on content here: [OLE Wagtail](https://docs.google.com/document/d/1MiY9keSutVx4GPePnZKRMXqbRCPrz6eET64b4PQ0qWM/edit?usp=sharing)

I've created a new [OLE wiki page](https://wiki.mozilla.org/Open_Leadership_and_Events) that covers most of the content that isn't going to move to MozFest site.  The only remaining items "to do" are: 

- [ ] what to do with old [Open Leadership program site](https://foundation.mozilla.org/en/initiatives/mozilla-open-leaders/) which is currently housed on Foundation site. 
- [ ] what to do with our open mtg notes

I suspect we need to have a bigger discussion around the first w/ @anilkanji ?  the second we will discuss within our team but it doesn't need to stop decommissioning the OLE website.  It can be decided later.

**Comment by kristinashu** [comment]
Thank you @stephwright, Kristina G, Marc for reviewing and compiling all that content!

Since I'm not as familiar with all the content, I felt I needed a higher level view of all the existing OLE wagtail pages so I've listed the urls [in this doc](https://docs.google.com/document/d/1qBHbGlPp8y7mLfBexH4wKNLmeusIo4d_CcN7HyI-LXY/edit#heading=h.ikqb00gsxy6r). 

Based on your content doc and our wagtail pages, my generally summary is that all the key content should either be subpages on the mozfest site or subpages of [/artifacts](https://foundation.mozilla.org/en/artifacts). 

Should we have a quick chat to go over this? Or if it all makes sense to you then you could go ahead and start creating the new page on the mozfest site (keep them hidden for now) and /artifacts.

Once that's all done then we can delete the old pages and redirect the urls.

**Comment by stephwright** [comment]
Thanks @kristinashu .... I've added comments to your doc.  Most of it doesn't need to be artefacted and can just go away and/or redirect to the wiki.

I'll set up a mtg for the three of us b/c there are still a few outstanding questions in there.

Steph

**Comment by stephwright** [comment]
hi @kristinashu ... I reviewed the Open Events Guide for currency, per our discussion in the call.  It is all still current and the content is mostly time stable so should be fine going forward unless any external links break.  The only thing that needs to be changed is the section on the 2019 Sprint for Internet Health needs to go away.  Is that something you can do or do I need to ping Marc or Kristina G? https://foundation.mozilla.org/en/initiatives/open-events-guide/

**Comment by jamilasnell** [comment]
@kristinashu Should this be closed?
