### ISSUE TITLE
IA: shareout of the report to stakeholders

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4415]
Follow up from #4383 and blocking #4302.

The[ interview report ](https://docs.google.com/document/d/16GilewBBqr-sDknD9MroVy4QHR3TmWl4Q_2kGXFDg4A/edit#heading=h.rrt26f1h8iqp)is done and is amazing!

### Todo
- [x] Draft email to send out the report to Anil, the rest of the engagement team, and all interviewed stakeholders
- [x] Send out the email
- [x]  Consider holding an office hour for it

cc @beccaklam

**Comment by taisdesouzalessa** [comment]
[Condensed report here - from slide 12 on](https://docs.google.com/presentation/d/19etCN1uGLcLmB50-uV-srsWKEAhlwlR_bc0dLE1uW1g/edit?usp=sharing)

**Comment by kristinashu** [comment]
Yay!

Note from https://github.com/mozilla/foundation.mozilla.org/issues/4416#issuecomment-605305636.

> Next step: Craft the email ([check this checklist](https://docs.google.com/document/d/1Bm2F7anspI3Nshgg67tZYVnVeFdIqk1Ye2XRcZldzjk/edit?usp=sharing)) and share with interviewees and Engagement team.

**Comment by taisdesouzalessa** [comment]
Email draft included in the checklist doc. Waiting for approval before sending it \0/

**Comment by taisdesouzalessa** [comment]
Email sent!
**Next step:** find a time that works the best for the majority of people to book the office hour.

Once I book the office hour I'll close this ticket.

**Comment by taisdesouzalessa** [comment]
Office hours booked to April 2nd (10-10:45am PT). [FAQ sheet here](https://docs.google.com/document/d/1-sQmy90XM6iu1J3Gkuu4xQj3Ea0QSnV6Xv9bFo982_Q/edit?usp=sharing).

Closing this ticket 
🙏
