### ISSUE TITLE
IA: Epic for sharing out the report

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4418]
To dos

- [x] IA: add Bob's insights to the report #4383
- [x] IA: Create a condensed report #4416
- [x] IA: Share out of the report to stakeholders #4415
- [x] IA: Create a short intro to IA work #4417
- [x] IA: shareout of the report to all staff #4302

**Comment by kristinashu** [comment]
The bulk of this work is done so I'll close this epic. Remaining work is happening in https://github.com/mozilla/foundation.mozilla.org/issues/4302
