### ISSUE TITLE
[meta-ticket] Proposed IA

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4438]
## Todo

**Proposed IA**
- [x] [Create proposed IA](https://redpen.io/p/wd83cac5211b178ff0) [#4244] (Apr 6)
- [x] Share with the team and iterate based on feedback [#4439] (Apr 6)

**Prototype**
- [x] Create high-level wireframes for each parent page & a prototype [#4465] (Apr 20)
- [x] Share with the team and iterate based on feedback [need ticket]
- [ ] Share with all staff [need ticket]
- [x] Find a few people from our audience [ #4114] (Apr 6)
- [ ] Test with a few people from our audience [need ticket]

**Notes (edited by Taís):**
- [ ] Once we have a new URL structure to Initiatives/Awards and Fellowships, please inform Audrey to contact Torchbox (they will need to update GA ads that are pointing to those urls).
