### ISSUE TITLE
[Fellows support] Responsible Computer Science Playbook: Epic

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#4451]
### Background
The Responsible Computer Science Playbook is an online guide that will surface the expertise of 17 universities about how to bring ethics to Computer Science curriculum.

### Problem it is trying to solve
To have a reliable “how to” guide for bringing ethics in CS to curriculum.

### Resources
[Stakeholder Interview doc](https://docs.google.com/document/d/1YxB0-c47io_WaJZq1vkQq39RMuNhXqfXJ8f6dBdJZKU/edit?usp=sharing)
[Meeting notes](https://docs.google.com/document/d/1lT0UM3v8fPGMtnTOM9FXJQ8KidKGPqOwn6WAs8UuhBo/edit?usp=sharing)

**Next steps:**
THEME: INSPIRATION AND REQUIREMENTS (#4452)
- [x] Look at some playbook benchmarks to get inspiration. Examples: [U.S. Digital Services  Playbook](https://playbook.cio.gov/#play1) and [Atlassian Team Playbook](https://www.atlassian.com/team-playbook) 
- [x] Start some hand drawn mock ups considering Wagtail restrictions
- [x] Project needs: can we give access to a few non-mozilla people to the specific section?

THEME: CREATE AND BUILD (#4453)
- [x] Mock up a couple options using wagtail 
- [x] Get feedback from design team and Kathy
- [x] Set up the chosen proposal in Wagtail 
- [x] Consider how it fits in with other [Responsible CS Challenge work](https://foundation.mozilla.org/en/initiatives/responsible-cs/) 
- [x] Train Kathy to add the rest of the content herself

THEME: CS CHALLENGE AND SUPPORT (#4719)
- [x] Do a quick prototype based on email conversation around "Consider how it fits in with other Responsible CS Challenge work"
- [x] Support Kathy in case she has any issues

THEME: GRAPHICS AND RCS MAIN PAGE (#4616)
**Note: dependence on copy + links for the [RCS main page](https://foundation.mozilla.org/en/initiatives/responsible-cs/)**
- [ ] get feedback from Kathy on the [prototype suggested](https://mozilla.invisionapp.com/share/3KX6DXKF5VM#/screens/421310516) in #4719 (requested by email)
- [ ] after getting copy + links from Kathy and Jenn (requested by email), build it on prod
- [ ] do the illustrations

**Note: dependence on Kathy populating the page with content**
- [x] Create a banner graphic that aligns with the existing CS branding
- [x] Create graphics to individual articles once we have all the content on the page

THEME: HANDOFF (#4454)
- [ ] Deliver jpgs/png/layered file of the banner so Kathy can use it for different projects
- [ ] Do a design pass of the all the pages once they are ready
- [ ] Make sure everybody who needs to have access to this page have the permission (list will be sent by Kathy)
- [ ] Remove password protection and launch page!

**Comment by taisdesouzalessa** [comment]
@Pomax I will be working on this issue to support a Fellow and I was wondering if we can give Wagtail access to a small group of people with these parameters:

1. They are not Mozillians (**no Mozilla email**)
2. Restricted access to see and edit only a **very specific group of pages**

Is this possible and are there any risks associated with this request we should be aware of? Thanks!

**Comment by Pomax** [comment]
1) as long as they have a g account, we should be able to grant them access to the cms
2) we can set up a special group for them that only gives them access to "nothing, except login rights, and the exactly pages X, Y, ..."

**Comment by taisdesouzalessa** [comment]
Thank you so much for your reply, Pomax! I sent an email to Kathy (the owner of this project) requesting an email address (Gmail) list of people who will need edit privileges to this specific Wagtail page.

**Comment by taisdesouzalessa** [comment]
changed this epic to reflect current process.
