### ISSUE TITLE
PNI: design PNI Video Call App updates

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4456]
### Todo
- [x] Mockup new template page based on [content doc](https://docs.google.com/document/d/1IBNGYZAdqIZj953eHhJmRxFDjtvvT_5Z5PYYElTo6iQ/edit) and [spreadsheet](https://docs.google.com/spreadsheets/d/1Yed1uRtDfFonbHb0Uew3SsCnXB0nNvpkKCg8QKe9X3c/edit#gid=1515398276)
  - keep styles as close as possible to existing styles
  - consider adding an extra about this special edition section (below blurb)
- [x] Add "Video call apps" to nav (consider adding an icon)
- [x] Design graphic treatment for product image
- [x] Mockup homepage with a few examples of apps integrated with iot products

cc @Pomax @cadecairos

**Comment by cadecairos** [comment]
@mmmavis

**Comment by natalieworth** [comment]
I've added mockups for the nav, graphic treatment options for the product images, and I've mocked up the homepage with some of the image examples with the other products. All in the [redpen here](https://redpen.io/p/rf0f1dc60ad1ca80e4).

Just waiting on final-ish copy for 1 video app and then I will do mockup for the new template and about this section blurb page.

cc @kristinashu @mmmavis

**Comment by natalieworth** [comment]
Added the product page mockup for desktop here (V2):
https://redpen.io/p/rf0f1dc60ad1ca80e4

cc @kristinashu @mmmavis

**Comment by natalieworth** [comment]
I’ve also started collecting the logos/ assets for each [video product in here](https://drive.google.com/drive/u/0/folders/1hcmlTPDUoPPaN0DWgHP6fAYHRGWEpSol).

I have GoToMeeting, Houseparty, Jitsi, Microsoft Teams, Signal, Skype, and WhatsApp remaining.

**Comment by natalieworth** [comment]
And just to confirm what's been done/ if it could be R+'d:
- We're using the Video logos for the Homepage images [homepage design is here](https://redpen.io/tr8fa7796345d91d1f)
- Added video call apps + icon in [nav here](https://redpen.io/tr8fa7796345d91d1f)
- Graphic treatment for product page [includes the product + the logo](https://redpen.io/zq699456aa063e945a)
 
-------

- Mockup of [new template page](https://redpen.io/zq699456aa063e945a)

-------

To do/ remaining:
- extra about this special edition section (below blurb)

**Comment by kristinashu** [comment]
These look awesome Nat!

> - We're using the Video logos for the Homepage images [homepage design is here](https://redpen.io/tr8fa7796345d91d1f)
> - Graphic treatment for product page [includes the product + the logo](https://redpen.io/zq699456aa063e945a)

Sorry Nat but you're going to have to choose one treatment that will work for both the homepage thumbnails and the product detail page. Right now we only allow for one image to be uploaded and I think we should keep it that way, at least for now. Adding two images will be more work for devs and also for designers to maintain and QA. (note: this deciding which treatment and exporting all the images isn't a blocker for devs)

-------

> - Added video call apps + icon in [nav here](https://redpen.io/tr8fa7796345d91d1f)

Nice!

-------

> - Mockup of [new template page](https://redpen.io/zq699456aa063e945a)

This looks great! @Pomax @mmmavis any concerns?

**Comment by natalieworth** [comment]
Updated the last few changes based on Jen's feedback yesterday. 

For design, final [video logos are in here](https://drive.google.com/drive/u/0/folders/1hcmlTPDUoPPaN0DWgHP6fAYHRGWEpSol) and I can start creating the images for the tiles today

**Comment by natalieworth** [comment]
Cropped and edited images [are in here](https://drive.google.com/drive/folders/1gw9XEz4fgkGBdBKP5C84_5mGnzkzPrRm?usp=sharing).

**Comment by kristinashu** [comment]
Looks excellent Nat! R+ 

Let's share these at stand to see if devs have any concerns.

Side note: you could still use the app UI graphics for marketing.

**Comment by mmmavis** [comment]
> [Updated the last few changes](https://redpen.io/p/rf0f1dc60ad1ca80e4) based on Jen's feedback yesterday. 
![image](https://user-images.githubusercontent.com/2896608/79253299-d2040000-7e37-11ea-97c3-87406a98dc32.png)

@natalieworth there are many versions of mockups. Can you point me to the ones that are _close to final_.

**Comment by natalieworth** [comment]
Video Icon (svg) [is here](https://drive.google.com/drive/folders/1uJCXQui-utsFPyr-3L6YAWlDJX3jWxph?usp=sharing).

[Uploading Icons.zip…]()

**Comment by kristinashu** [comment]
@mmmavis Natalie has updated [redpen](https://redpen.io/p/rf0f1dc60ad1ca80e4) so it should be clear now. Unless you have any feedback, these designs are final. 

Mavis, do you want me to try opening the implementation tickets for this or will you? I'm assuming the tickets needed are:
- Add icon to main nav
- Update text, order, and styling for these sections (not sure if they should be 1 or 3 or more tickets)

<img width="425" alt="image" src="https://user-images.githubusercontent.com/1068783/79281648-0d1e2780-7e68-11ea-9338-3c0c72db2651.png">

**Comment by mmmavis** [comment]
I left 2 small comments on the product page mockup. Will create dev tickets tmr.

**Comment by mmmavis** [comment]
I have updated the implementation ticket: https://github.com/mozilla/foundation.mozilla.org/issues/4488. Since design has been finalized, I will be using Sketch file as my design reference. 👍
