### ISSUE TITLE
User test wireframe prototype - part II

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#4674]
Blocked by part I (#4650) + treejack findings (#4649) + more refined content to populate wireframes

Test our [new proposed wireframes](https://mozilla.invisionapp.com/share/ZEWXZW3VXJR#/screens/414389585) using usertesting.com with a focus on novice users.

### Todo - part II
- [ ] Read final report on Treejack learnings.
- [ ] Iterate on wireframes based on learnings from the Treejack test
- [ ] Add the more refined content to the wireframes (Anil is currently working on that)
- [x] Let MoCo know. UPDATE: **talked to Raja and he asked to be informed of out test 2 days in advance to arrange our access to the platform**
- [ ] Run test
- [ ] Compile and analyze feedback

**Comment by taisdesouzalessa** [comment]
not relevant anymore. We skipped this task and did user testing on the live site, once changes were already implemented.
