### ISSUE TITLE
[IA refresh] Press Center page

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#4766]
**Tasks:**
- [x] 1. build a press center page in the "ai refresh environment"
- [x] 2. to do a mockup showing how the link can be displayed on the page footer (include mobile and tablet)
- [x] 3. get approval from Design and Kevin
- [x] 4. Have a conversation with Kevin about the sites affected by this change (all properties including Pulse, PNI and MozFest?
- [x] 5. Update Abstract and do illustration
- [x] 6. Build the page in the current live environment (step 1: get permission/step 2: build) -  #4777
- [x] 7. Open implementations ticket for footer (tag Théo for localization as per conversation with Kevin below). 
- [x] 7a. for Foundation site and PNI - ticket here: #4791
- [x] 7b. For MozFest - ticket here:  #4824
- [x] 7c. For donate page (donate.mozilla and thunderbird) - connected with Will, who approved the changes (ticket [here for donate](https://github.com/mozilla/donate-wagtail/issues/1017) and [here for thunderbird](https://github.com/mozilla/donate-wagtail/issues/1018))

**Comment by taisdesouzalessa** [comment]
1. Press Center Page here:
https://ia-refresh.mofostaging.net/en/press-center/

2. Footer mockup:
<img width="1407" alt="image" src="https://user-images.githubusercontent.com/22157921/84072980-e15d8080-a984-11ea-942b-30a075af9cc7.png">

@kristinashu @beccaklam are you both okay with this quick solution for the footer for now? We may have to rethink the footer once we include the new legal message ( #4755)

**Comment by kristinashu** [comment]
The placement looks good to me Tais!

Additional tasks would be to mock it up for tablet and mobile (this case should be pretty straightforward but it's good practice to do it). Once approved by a designer, the Abstract style guide needs to be updated and merged. For the implementation ticket, make sure you note all the different sites that would be affected by this update.

**Comment by taisdesouzalessa** [comment]
@KevZawacki I was wondering which sites should be affected by the "press center" footer update. Would you like to have this on the footer of all our properties? 

[Foundation site](https://foundation.mozilla.org/en/)
[MozFest site](https://www.mozillafestival.org/en/)
[PNI site](https://foundation.mozilla.org/en/privacynotincluded/)
[Pulse site](https://www.mozillapulse.org/)

**Comment by KevZawacki** [comment]
Hi @taisdesouzalessa, I think all except Pulse

**Comment by taisdesouzalessa** [comment]
@KevZawacki I added 2 more donate sites to the list. I failed to add them previously, sorry for that. Can you confirm you want the "Press Center" on them as well?

@mmmavis is it possible to hide an item in some footers and display it in others? Just wondering about the complexity of this request on the development side.

**Comment by KevZawacki** [comment]
@taisdesouzalessa Yes please, let's include the Press link on the donate sites, too.

And if it is difficult to hide an item in some footers and display it in others, no problem -- we can simply have the Press footer on all pages.

**Comment by taisdesouzalessa** [comment]
Thanks for your feedback, @KevZawacki ! I have 2 more questions that came to mind while I was [doing the mockup for all the footers](https://mozilla.invisionapp.com/share/53XMQ5EJ7PZ#/420962395_Press_Center):
• The [MozFest site](https://www.mozillafestival.org/en/) footer already has a link called  "Media Center", which takes users to [this page](https://www.mozillafestival.org/en/media/). Should we keep the MozFest site as is or you want to update it?
• We will roll the update to all our English properties. I wonder if you have any insight on how to do the localized versions? Do you want this link on the footer + page in the localized versions as well?

**Comment by mmmavis** [comment]
> @mmmavis is it possible to hide an item in some footers and display it in others? Just wondering about the complexity of this request on the development side.

Footer is not customizable. Just like site nav, I think footer should stay the same across the same site. Any reason we would like to modify it on a per page basis?

**Comment by kristinashu** [comment]
@mmmavis I think @taisdesouzalessa is talking about having different links on different sites (e.g. mozfest site would have a different link than the foundation site). But all pages within a site would have the same footer (e.g. all mozfest pages would have the exact same footer links).

**Comment by KevZawacki** [comment]
Hi @taisdesouzalessa,

>The MozFest site footer already has a link called "Media Center", which takes users to this page. Should we keep the MozFest site as is or you want to update it?

We can keep the MozFest Media Center page as is.

>We will roll the update to all our English properties. I wonder if you have any insight on how to do the localized versions? Do you want this link on the footer + page in the localized versions as well?

I think we should put the link + page on localized versions, even if it's still in English. If we localize the page, we might give the false impression that our Communications Team (me) speaks the language 😂 And in my experience, most journalists in France/Germany/Spain/etc. speak English

**Comment by mmmavis** [comment]
@taisdesouzalessa ah gotcha. Yea different links for different sites sounds good.

**Comment by taisdesouzalessa** [comment]
This work is moving to next sprint because we still need:
1. to create the page in prod
2. update Abstract
3. Get Marc's permission to modify the MozFest "Media Center" Page in the future

**Comment by taisdesouzalessa** [comment]
@KevZawacki this is the final Press Center page, with custom illustration: https://foundation.mozilla.org/cms/pages/970/view_draft/ (you have to log in to Wagtail to see the page)- please let me know if you need any design tweak. 
You can change the content as you wish. 

Once you are okay with the page, let me know and we can publish it, so you can send the link to press as needed. The next step is to have footer links to make this page discoverable - the tickets to engineers were created and the task is in their queue.

**Comment by KevZawacki** [comment]
Hi @taisdesouzalessa, this is perfect -- thank you! Ready to publish!

**Comment by taisdesouzalessa** [comment]
Published! This is the link: https://foundation.mozilla.org/press-center/

**Comment by kristinashu** [comment]
Yay, looks great!

cc @TheoChevalier so this is on your radar. Note, we will be adding a footer link to this page.

**Comment by TheoChevalier** [comment]
Thanks! I can confirm we will just translate the link in the footer of the various web properties, and keep the actual page in English

**Comment by taisdesouzalessa** [comment]
Page done, updated on Abstract and launched. Thanks all!
@TheoChevalier I tagged you in the implementation tickets for all the footers. Please let me know if you have any questions.
