### ISSUE TITLE
[IA refresh] UI design (all pages except home page)

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#4772]
### Background
Based on [the wireframes](https://mozilla.invisionapp.com/share/7WXCS62FVXH#/418292231_Desktop_Home) of our IA refresh, it is time to do the UI design.

While doing this work we should also be aware of what is happening here: #578 so there is no duplicated efforts. 

### Pages to be designed
- [x] Home page - **Status: in progress #4648**
- [ ] All pages under "Who we are" section - **Status: blocked by** #4668
- [x] All pages under "What we do" section - **Status: up next #4776**
- [x] All pages under "What we fund" section - **Status: blocked by content from execs**
- [ ] We should also review our "What you can do" page to make sure the UI aligns with the rest of the pages. - **Phase II** 

### References:
[Wireframes](https://mozilla.invisionapp.com/share/7WXCS62FVXH#/418292231_Desktop_Home)
[Live IA refresh environment](https://ia-refresh.mofostaging.net/en/)

Assigning Kristina to decide designer who will work on them.
