### ISSUE TITLE
[IA refresh] What we do

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4776]
Explore different graphic directions for the [What we do pages](https://mozilla.invisionapp.com/share/7WXCS62FVXH#/screens/418292842).

### Things to explore
- Different banner treatments - related to https://github.com/MozillaFoundation/Design/issues/578 and https://github.com/MozillaFoundation/Design/issues/583
- How to balance photography (treated and untreated) (related to https://github.com/MozillaFoundation/Design/issues/516), evergreen illustration style (like on our current [/initiatives](https://foundation.mozilla.org/initiatives) page), and other illustration styles (like PNI, blog posts, petitions...)
- Different dimensions and shapes for images and when (e.g. round, cut out, square, different ratios of rectangle)

### Task to complete
- [x] Explore three different directions
- [x] Get feedback from the design team
- [x] Chose one direction (doesn't have to be final images but should represent the style direction)
- [ ] Update the staging site
- [x] Open any necessary tickets

**Comment by beccaklam** [comment]
So I'm struggling with this quite a bit. On the overview page if we use a photo banner it feels like it'll be better if the rest of the page is more uniform in some way, see [Test 1](https://redpen.io/bt51efa231b523ce59) vs [Test 2](https://redpen.io/ekd4631c1e2c9327f6). Using multiple photos on the page feels too busy. I wonder if the project examples we show on the overview page can be more high level categories (e.g. campaigns vs a specific campaign) this way it would be more future-proof. On the individual pillar's pages we can keep the more up to date specific project examples. Thoughts? @kristinashu @taisdesouzalessa @sabrinang @natalieworth

**Comment by beccaklam** [comment]
We chose this direction: https://redpen.io/ekd4631c1e2c9327f6 but it still needs finessing for final assets. Opened follow up ticket here: #4872
