### ISSUE TITLE
[donate.mozilla.org] Update OG image 

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#4819]
### Background
Our current OG image is outdated. We should update to one more aligned with our current brand standards and new strategy.

### Screenshot of current OG
<img width="695" alt="image" src="https://user-images.githubusercontent.com/22157921/85614000-54b2f380-b60f-11ea-9795-4bf0287e7796.png">

### Specs
The current OG is 1200px_600px. [View image here](https://assets.mofoprod.net/images/og.png)

### Tasks
- [x] To develop 2 or 3 options. Please loop Will in (or anybody else that looks after this page)
- [x] Get approvals from designers + Will
- [x] File the implementation ticket on `donate-wagtail GH repo`

PS: filing this ticket here so it shows up in our Foundation board.

**Comment by sabrinang** [comment]
For donation photos typically we want the logo prominent and a good photo. I looked at some tips from a [nonprofit blog](https://www.networkforgood.com/nonprofitblog/how-choose-best-pictures-use-your-online-donation-software/). I explored some options from our photo library:

<img width="1606" alt="image" src="https://user-images.githubusercontent.com/2492510/97763616-62025200-1ac9-11eb-9f5e-ba5c25a04cfc.png">

**Comment by taisdesouzalessa** [comment]
Those look great, Sabs! I also love the fact you found a source with tips for nonprofits. I think any of them would work, those are all great pictures.

**Comment by sabrinang** [comment]
I exported the OG image ideas for donate.mozilla.org in redpen here: https://redpen.io/p/db9f5de9719c12a64a

Please review or leave any feedback @kristinashu @natalieworth @taisdesouzalessa @WillatMozFdn

**Comment by sabrinang** [comment]
exports of all og images are in gdrive here: https://drive.google.com/open?id=1BrNxynsfv5uG-NxWCt7zdLI6jklcGXYC&authuser=sabrina%40mozillafoundation.org&usp=drive_fs

**Comment by WillatMozFdn** [comment]
Hey Sabrina, thanks so much!!!  Let's go with mozilla-foundation_donation-og-image_1@2x (the one at upper left in the 3 x 2 montage up there ^^ in this thread, guy at Mozfest pointing while some kids look on.)  Generally speaking I like it the best (action-oriented, has diversity of people/races/ages), but also -- it has a long history of use as the default image on our donate page. We're slowly moving traffic away from that default page (and onto wagtail banner-style pages like this one https://donate.mozilla.org/en-US/sept2020/ ) ... but, the familiarity with the old photo will definitely be a big plus for anyone that's previously donated, or visited the page but then abandoned.  Familiarity brings comfort, and comfortable people make more & bigger donations.  :-) 

Does that sound good?  thanks again!!!

**Comment by sabrinang** [comment]
Great thanks for review Will and we can go with [mozilla-foundation_donation-og-image_1@2x ](https://drive.google.com/file/d/1CVJSegDKRD5ZbeiUrLX3n0NxPVJnsPJQ/view?usp=sharing) 

I filed the implementation ticket here: https://github.com/mozilla/donate-wagtail/issues/1207
