### ISSUE TITLE
Insights (IHR): Email signup viability

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4848]
Data Stewardship work would like an email signup. We think the IHR list could work this but the snippet copy and the email on boarding text will need to be updated to something that will work for both the [IHR page](https://foundation.mozilla.org/en/internet-health-report/) and Data Stewardship page (coming soon).

Snippet copy is easy to update but email will rely on @stephaniemcv.

### Todo
- [x] Confirm with Steph that she could update the email and subscription page
- [x] Confirm with Insights team that they definitely want to make this shift _(I recommend this list becomes a "research and insights" type list that would include projects like IHR, Data Stewardship, and Trustworthy IA Landscape Analysis...)_
- [x] Confirm with Anil that this is the right approach 

#### Screen cap of subscription page

![Screenshot_2020-07-03 Newsletter Subscriptions](https://user-images.githubusercontent.com/1068783/86490999-35f2e200-bd1e-11ea-8935-7abf1304e15b.png)

#### Screen cap of welcome email

(waiting for the email...)

#### Screen cap of snippet copy

<img width="1343" alt="image" src="https://user-images.githubusercontent.com/1068783/86490992-2c697a00-bd1e-11ea-8208-a45a0b886f97.png">
 

cc @taisdesouzalessa

**Comment by taisdesouzalessa** [comment]
@kristinashu are we adding the email sign up on the Data Futures pages as well? If so, please ping me when this task is finished so I can add the snippet to the pages. Current page screenshot:

<img width="608" alt="image" src="https://user-images.githubusercontent.com/22157921/92944782-46ec5d80-f409-11ea-9afe-793726bff5a4.png">
