### ISSUE TITLE
Define URL structure: engineer support and redirect map

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#4999]
Now that the structure is defined (#4917), we have to connect with Engineers and also create a map showing current URLs and the new destination URLs so we can do proper redirects.

**Task list:**
- [ ] Identify areas that will need Engineer support
- [ ] talk to Engineers about the areas identified above and also try to better understand how the automatic redirect of URLs in Wagtail work
- [ ] do the redirect map
- [ ] connect with Raphael Raue (Global Head of SEO) from MoCo to make sure we are not missing anything

### **Relevant links:**
[Proposed structure here (second tab)](https://docs.google.com/spreadsheets/d/184z7LnHIghXDp2NIns4T8zlpBDAdaRFuPMUDX7ijHYY/edit?usp=sharing)

Resources: 
[Report on URLs and rationale](https://docs.google.com/document/d/1kqYux6AI1SNNu0vJI5FVFLl9gUFD_aL7CjB6SETp-Hw/edit?usp=sharing)
[Visual mapping of IA + URLs](https://kumu.io/taislessa/url-structure-v2#v2-map)

**Comment by taisdesouzalessa** [comment]
Started work in this sprint, couldn't finish it mainly to this task being more complex than anticipated +  work on design reviews for homepage. Status: around 55% done and ticket created for next sprint. #5068
