### ISSUE TITLE
[URL structure] EPIC: clean up wagtail and update redirect map 

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#5068]
Work started here:  #4999

We've already done some of the redirects work in individual tasks and it would be good to update our map to reflect the redirects we already have in place and to identify what's missing. This ticket is an epic, containing little tickets that support redirect map and cleaning up our Wagtail

The structure was defined  in #4917

**Task list:**

- [ ] [URL structure] Update current URLs [#6293](https://github.com/mozilla/foundation.mozilla.org/issues/6293)
- [ ] [URL Structure] Initiatives pages [#6294](https://github.com/mozilla/foundation.mozilla.org/issues/6294)
- [ ] [URL Structure] Advocacy and Campaigns URLs [#6295](https://github.com/mozilla/foundation.mozilla.org/issues/6295)
- [ ] [URL Structure] Redirect mapping: "who we are", "press center", "what we do" and "artifacts" [#6296](https://github.com/mozilla/foundation.mozilla.org/issues/6296)
- [ ] [URL Structure] Insights and Data Futures Lab [#6297](https://github.com/mozilla/foundation.mozilla.org/issues/6297)
- [ ] [URL Structure] Fellowships and Awards Hub [#6298](https://github.com/mozilla/foundation.mozilla.org/issues/6298)
- [ ] [URL Structure] Newsletter and Giving [#6299](https://github.com/mozilla/foundation.mozilla.org/issues/6299)
- [ ] [URL structure] "What you can do", "blogs", "docs" [#6300](https://github.com/mozilla/foundation.mozilla.org/issues/6300)

### **Relevant links:**
[Proposed structure here (second tab)](https://docs.google.com/spreadsheets/d/184z7LnHIghXDp2NIns4T8zlpBDAdaRFuPMUDX7ijHYY/edit?usp=sharing)

Resources: 
[Report on URLs and rationale](https://docs.google.com/document/d/1kqYux6AI1SNNu0vJI5FVFLl9gUFD_aL7CjB6SETp-Hw/edit?usp=sharing)
[Visual mapping of IA + URLs](https://kumu.io/taislessa/url-structure-v2#v2-map)

**Comment by taisdesouzalessa** [comment]
moving this to next sprint. There was no time for this task during the past sprint.

**Comment by jamilasnell** [comment]
@taisdesouzalessa Could this be an epic?

**Comment by taisdesouzalessa** [comment]
Updated the ticket, removed the epic label and added an estimate.

**Comment by taisdesouzalessa** [comment]
@jamilasnell this has to be moved to Jan 2021 :)

**Comment by taisdesouzalessa** [comment]
Broke down this ticket in some manageable pieces:
- [URL structure] Update current URLs [#6293](https://github.com/mozilla/foundation.mozilla.org/issues/6293)
- [URL Structure] Initiatives pages [#6294](https://github.com/mozilla/foundation.mozilla.org/issues/6294)
- [URL Structure] Advocacy and Campaigns URLs [#6295](https://github.com/mozilla/foundation.mozilla.org/issues/6295)
- [URL Structure] Redirect mapping: "who we are", "press center", "what we do" and "artifacts" [#6296](https://github.com/mozilla/foundation.mozilla.org/issues/6296)
- [URL Structure] Insights and Data Futures Lab [#6297](https://github.com/mozilla/foundation.mozilla.org/issues/6297)
- [URL Structure] Fellowships and Awards Hub [#6298](https://github.com/mozilla/foundation.mozilla.org/issues/6298)
- [URL Structure] Newsletter and Giving [#6299](https://github.com/mozilla/foundation.mozilla.org/issues/6299)
- [URL structure] "What you can do", "blogs", "docs" [#6300](https://github.com/mozilla/foundation.mozilla.org/issues/6300)

@kristinashu @jamilasnell above is my attempt in breaking down the ticket into manageable pieces. I will need your help to triage and prioritize them into next sprints. The first ticket (#6293) was 90% done during this past sprint (finishing it today). I also added the Insights and Data Futures Lab (#6297) to my queue this sprint since it makes sense to update this while I work on DFL and Insights support this sprint.

Feel free to change things around and add comments to individual tickets. Thanks!

**Comment by kristinashu** [comment]
Wonderful, thank you Tais! 

Do you want to turn this into an Epic and then add the tickets you just opened to it?
<img width="348" alt="image" src="https://user-images.githubusercontent.com/1068783/109709558-83e01400-7b51-11eb-8981-23f0cd3c696b.png">

**Comment by taisdesouzalessa** [comment]
I think this is a great idea. To keep them all tied together! Tks for the suggestion.

**Comment by Pomax** [comment]
@kristinashu can this be closed, or is there more work we want to do here?
