### ISSUE TITLE
Update content on the product details page

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#5234]
This is the overarching task issue for updating the product details template. It can be closed when all dependencies have been resolved.

**Comment by Pomax** [comment]
Original comment, just so that it's preserved for now:
------
### Task list

- [ ] Move price link below product name, estimate: 1
- [ ] Remove ‘copy & share link’, estimate: 2
- [ ] Update font style for into blurb, estimate: 2 (maybe 3)
- [ ] Add “wifi” and "bluetooth" icons where applicable, 2
- [ ] Style and move “What could happen if something goes wrong” up, estimate: 3
- [ ] Move “creep-o-meter” up - related to styling #5236 , estimate: 3
- [ ] Update section titles, estimate: 1
- [ ] Reorder criteria, estimate: 2
- [ ] Add new criteria, estimate: 3
- [ ] Move Security section down - related to styling #5237, estimate: 2~3 if not a duplicate
- [ ] Add accordion style where applicable (New work), 3 (maybe 5)
- [ ] Add ding when and where applicable - related to styling #5238, estimate 2 if not a duplicate

total estimate: 25ish

---

###  Design -> Dev Handoff Checklist

- [ ] Design has been finalized
- [ ] Link to original design ticket - #5152
- [ ] Link to related ticket - backend #5241
- [ ] Link to Redpen - https://redpen.io/p/yqece0a9215e9c33f1
- [ ] Design changes been merged into the master Sketch file
- [x] Desktop and mobile mockups are included
- [ ] Assets are included
- [ ] Hover state for elements are designed
- [ ] Other states for elements are designed (e.g., error state for form)

**Comment by Pomax** [comment]
all tasks were completed
