### ISSUE TITLE
Creep-o-meter work

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#5236]
### Todo backend (estimate: 2)
- [ ] double checking that things still work purely with the frontend removed

possibly, but we're not sure (follow up if necessary), not estimating unless necessary

- [ ] Backup/preserve likely-to-buy data for existing products ([cade] let's run a query for this data and back it up in our S3 archives for potential future use)
- [ ] Remove ‘Likely to buy’ backend models
- [ ] Remove 'Likely to buy' stats aggregation during manage.py

Note that removing the likely/unlikely to buy also allows us to clean up the statistics code and the aggregation commands on the python side (but let's make sure to capture a snapshot of this data before we migrate it out of existence!)

### Todo frontend (estimate: 3)
- [x] Remove ‘Likely to buy’ question 
- [x] Remove ‘Likely to buy’ results 
- [x] Remove "Tell us what you think" banner
- [x] Restyle "How creepy do you think this is?" title to match other headings on production
- [x] Replace outline with grey background `#f4f4f4` (should match banner grey)
- [x] Update button to `.btn_pop` style from [style guide](https://foundation.mozilla.org/en/style-guide/)
- [x] Expand the width of the creep-o-meter 
- [x] Expand the width of creep-o-meter results screen (note: should already be expanded on mobile)
- [x] Keep the newsletter sign up prompt the same

### Creep-o-meter currently looks like:
![image](https://user-images.githubusercontent.com/177243/93266509-03725600-f75f-11ea-8e11-4b81b9258e5a.png)

### New desktop comp 
https://redpen.io/va5424e577adb0d331
<img width="766" alt="image" src="https://user-images.githubusercontent.com/1068783/93280801-5a882300-f77f-11ea-97af-e48392cd1e2e.png">

<img width="750" alt="image" src="https://user-images.githubusercontent.com/1068783/93280815-6542b800-f77f-11ea-9ae8-1fda0c5144e5.png">

<img width="752" alt="image" src="https://user-images.githubusercontent.com/1068783/93280824-6c69c600-f77f-11ea-83a5-e0b1e370a12f.png">

### New mobile comp 
<img width="316" alt="image" src="https://user-images.githubusercontent.com/1068783/93526381-3d249780-f8ec-11ea-88b3-cc686656769b.png">

---

**🗒  Design -> Dev Handoff Checklist**

- [x] Design has been finalized
- [x] Link to original design ticket #5152
- [X] Link to related ticket #5234
- [x] Link to [Sketch file](https://share.goabstract.com/584e7002-4d07-4ce5-aafe-dc825e076a27?sha=f0b8ca1b588425d1ef83c57a9f4126c8ff97648e)
- [x] Design changes been merged into the master Sketch file
- [x] Desktop and mobile mockups are included
- [x] Assets are included - n/a
- [x] Hover state for elements are designed - same as on production
- [x] Other states for elements are designed (e.g., error state for form) - same as on production

**Comment by mmmavis** [comment]
PR merged!
