### ISSUE TITLE
Minimum Security Standard updates

### ISSUE THREAD

**Issue by jamilasnell** [mozilla/foundation.mozilla.org#5237]
### Todo
- [x] Hide MSS badge from hero banner
- [x] Re-style the criteria section (only use font styles that are already in use on production)
- [ ] Add accordion (default state is closed) - will be covered in #5257
- [x] Show privacy ding if answer is `No` - [icon](https://drive.google.com/drive/folders/1kPMOO9YoMybLN-MqziLUsmGE2EQ3hAVp?usp=sharing)
- [x] Move section down the page 

### Closed state desktop
<img width="862" alt="image" src="https://user-images.githubusercontent.com/1068783/93500801-6e3fa080-f8c9-11ea-93f2-ea15ed9e0ed1.png">

### Open state desktop
<img width="871" alt="image" src="https://user-images.githubusercontent.com/1068783/93500828-78619f00-f8c9-11ea-9c2a-300ba8e154ef.png">

### Closed state mobile
<img width="318" alt="image" src="https://user-images.githubusercontent.com/1068783/93509863-32123d00-f8d5-11ea-9aea-16f2e3176a7f.png">

### Open state mobile
<img width="251" alt="image" src="https://user-images.githubusercontent.com/1068783/93510130-9c2ae200-f8d5-11ea-87a7-e8ffcc49ead7.png">

---

###  Design -> Dev Handoff Checklist

- [x] Design has been finalized
- [x] Link to original design ticket #5152
- [X] Link to related ticket #5257
- [x] Link to [Sketch file](https://share.goabstract.com/584e7002-4d07-4ce5-aafe-dc825e076a27?sha=f0b8ca1b588425d1ef83c57a9f4126c8ff97648e)
- [x] Design changes been merged into the master Sketch file
- [x] Desktop and mobile mockups are included
- [x] Assets are included - [icon](https://drive.google.com/drive/folders/1kPMOO9YoMybLN-MqziLUsmGE2EQ3hAVp?usp=sharing)
- [x] Hover state for elements are designed - no hover state for the accordion / link: use what is on production
- [x] Other states for elements are designed (e.g., error state for form) - n/a

**Comment by mmmavis** [comment]
Gonna update this ticket as this is actually blocking the [Add accordion style to MSS ticket](https://github.com/mozilla/foundation.mozilla.org/issues/5257), instead of the other way around.

**Comment by mmmavis** [comment]
> Show privacy ding if answer is `No`

@kristinashu there's a checkbox `Show ding for minimum security standards` that's responsible for showing the ding. Is this field still needed? Or we want to show/hide the ding based on the value of `Meets minimum security standards` (which can be yes/no/unknown)

<img width="367" alt="image" src="https://user-images.githubusercontent.com/2896608/94617568-a1d1e180-025e-11eb-9a03-4b5d15ae73d3.png">

**Comment by kristinashu** [comment]
Oh sorry, Jen wants the manual checkbox. It will always be there for 'no' but it will be mixed for 'unknown' so it's safer if she can decide with the checkbox.

**Comment by mmmavis** [comment]
Alrighty!

**Comment by mmmavis** [comment]
Done!
