### ISSUE TITLE
Add "privacy" ding to upper portion of product page

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#5238]
### Todo
- [x] Add large privacy ding to hero when applicable - [icon](https://drive.google.com/drive/folders/1kPMOO9YoMybLN-MqziLUsmGE2EQ3hAVp?usp=sharing)
- [x] Add ‘Warning: *privacy not included with this product’ bar when applicable - #FBD545 / use font styles already in on production
- [x] Add mini privacy ding to `What could happen if something goes wrong?` - #5250
- [ ] ~~Add mini privacy ding when applicable (i.e. when the answer is `Yes` to the ding questions related to "How does it use this data?","How can you control your data?","What is the company’s known track record of protecting users’ data?","Does this product meet our Minimum Security Standards?") - [icon](https://drive.google.com/drive/folders/1kPMOO9YoMybLN-MqziLUsmGE2EQ3hAVp?usp=sharing)~~ Move to https://github.com/mozilla/foundation.mozilla.org/issues/5308

### Top section desktop
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/1068783/93502331-700a6380-f8cb-11ea-95ef-b67b34a4e442.png">

### Top section mobile
<img width="317" alt="Screen Shot 2020-09-18 at 1 00 15 PM" src="https://user-images.githubusercontent.com/1068783/93640327-3dd23200-f9af-11ea-8440-34664928b443.png">

### Criteria section desktop
<img width="840" alt="image" src="https://user-images.githubusercontent.com/1068783/93502391-857f8d80-f8cb-11ea-88d2-a3bc7e20d49f.png">

### Criteria section mobile
<img width="315" alt="image" src="https://user-images.githubusercontent.com/1068783/93502465-99c38a80-f8cb-11ea-9293-f5d4d088b223.png">

---

**🗒  Design -> Dev Handoff Checklist**

- [x] Design has been finalized
- [x] Link to original design ticket #5152
- [X] Link to related ticket #5234
- [x] Link to [Sketch file](https://share.goabstract.com/584e7002-4d07-4ce5-aafe-dc825e076a27?sha=f0b8ca1b588425d1ef83c57a9f4126c8ff97648e)
- [x] Design changes been merged into the master Sketch file
- [x] Desktop and mobile mockups are included
- [x] Assets are included - [icon](https://drive.google.com/drive/folders/1kPMOO9YoMybLN-MqziLUsmGE2EQ3hAVp?usp=sharing)
- [x] Hover state for elements are designed - n/a
- [x] Other states for elements are designed (e.g., error state for form) - n/a

**Comment by mmmavis** [comment]
My other ticket is blocked so gonna take this one on. For the last todo (see below) we'll have to tackle it in the MSS ticket.

![image](https://user-images.githubusercontent.com/2896608/94208570-02d47080-fe7f-11ea-8f21-9912f7f23b8d.png)

**Comment by mmmavis** [comment]
@kristinashu does this ticket include removing the MSS badge from the product page?

<img width="511" alt="image" src="https://user-images.githubusercontent.com/2896608/94319882-79857280-ff40-11ea-9347-41e4991305fd.png">

**Comment by kristinashu** [comment]
No, this one does https://github.com/mozilla/foundation.mozilla.org/issues/5237

**Comment by mmmavis** [comment]
Thanks!

**Comment by mmmavis** [comment]
⚠️ added!
