### ISSUE TITLE
Add “Wi-Fi” and "Bluetooth" icons where applicable

### ISSUE THREAD

**Issue by jamilasnell** [mozilla/foundation.mozilla.org#5249]
@jamilasnell commented on [Wed Sep 16 2020](https://github.com/mozilla/network-pulse/issues/1417)

### Add “Wi-Fi” and "Bluetooth" icons where applicable
- [ ] If answer is 'Yes' then show the icon (if the answer is no then hide the icon) - [icons](https://drive.google.com/drive/folders/1kPMOO9YoMybLN-MqziLUsmGE2EQ3hAVp?usp=sharing)
- [ ] Icon and text should be Gray 60 ($gray-60) #666666

### Desktop 
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/1068783/93522231-ffbd0b80-f8e5-11ea-9de0-6421841903eb.png">

### Mobile
<img width="316" alt="image" src="https://user-images.githubusercontent.com/1068783/93522384-3a26a880-f8e6-11ea-855a-677cbc1bfb28.png">

---

**🗒  Design -> Dev Handoff Checklist**

- [x] Design has been finalized
- [x] Link to original design ticket #5152
- [X] Link to related ticket #5234
- [x] Link to [Sketch file](https://share.goabstract.com/584e7002-4d07-4ce5-aafe-dc825e076a27?sha=f0b8ca1b588425d1ef83c57a9f4126c8ff97648e)
- [x] Design changes been merged into the master Sketch file
- [x] Desktop and mobile mockups are included
- [x] Assets are included - [icons](https://drive.google.com/drive/folders/1kPMOO9YoMybLN-MqziLUsmGE2EQ3hAVp?usp=sharing)
- [x] Hover state for elements are designed - n/a
- [x] Other states for elements are designed (e.g., error state for form) - n/a

**Comment by mmmavis** [comment]
@kristinashu could you export the icons without including the words (WiFi, Bluetooth)? Thanks!

**Comment by kristinashu** [comment]
I've added those to the folder - the old version with text is there but the "text" in the file name.
