### ISSUE TITLE
Style and move “What could happen if something goes wrong?” section

### ISSUE THREAD

**Issue by jamilasnell** [mozilla/foundation.mozilla.org#5250]
@jamilasnell commented on [Wed Sep 16 2020](https://github.com/mozilla/network-pulse/issues/1418)

Style and move “What could happen if something goes wrong?” section

- [x] Move the section up so it is below the blurb
- [x] Remove the old styling (outline, creepy face, center alignment)
- [x] Update heading "What could happen if something went wrong?": add `?` and make the style match the heading style that is on production
- [x] Body copy should be .body from [our style guide](https://foundation.mozilla.org/en/style-guide/) and match the blurb copy copy #5248 
- [x] Add the privacy ding symbol - [icon](https://drive.google.com/drive/folders/1kPMOO9YoMybLN-MqziLUsmGE2EQ3hAVp?usp=sharing)

### Desktop
<img width="824" alt="image" src="https://user-images.githubusercontent.com/1068783/93409011-c1bed980-f84a-11ea-8551-19cf9d5578d3.png">

### Mobile
<img width="318" alt="image" src="https://user-images.githubusercontent.com/1068783/93502551-bcee3a00-f8cb-11ea-8a09-908dca254ada.png">

---

**🗒  Design -> Dev Handoff Checklist**

- [x] Design has been finalized
- [x] Link to original design ticket #5152
- [X] Link to related ticket #5234
- [x] Link to [Sketch file](https://share.goabstract.com/584e7002-4d07-4ce5-aafe-dc825e076a27?sha=f0b8ca1b588425d1ef83c57a9f4126c8ff97648e)
- [x] Design changes been merged into the master Sketch file
- [x] Desktop and mobile mockups are included
- [x] Assets are included - [icon](https://drive.google.com/drive/folders/1kPMOO9YoMybLN-MqziLUsmGE2EQ3hAVp?usp=sharing)
- [x] Hover state for elements are designed - n/a
- [x] Other states for elements are designed (e.g., error state for form) - n/a

**Comment by mmmavis** [comment]
Done!
