### ISSUE TITLE
Add accordion style to MSS

### ISSUE THREAD

**Issue by jamilasnell** [mozilla/foundation.mozilla.org#5257]
Add accordion style to MSS

### Todo
- [x] Add accordion [icon](https://drive.google.com/drive/folders/1kPMOO9YoMybLN-MqziLUsmGE2EQ3hAVp?usp=sharing) (default state is closed) - related to #5237

### Closed state
<img width="862" alt="image" src="https://user-images.githubusercontent.com/1068783/93500801-6e3fa080-f8c9-11ea-93f2-ea15ed9e0ed1.png">

### Open state
<img width="871" alt="image" src="https://user-images.githubusercontent.com/1068783/93500828-78619f00-f8c9-11ea-9c2a-300ba8e154ef.png">

---

###  Design -> Dev Handoff Checklist

- [x] Design has been finalized
- [x] Link to original design ticket #5237
- [X] Link to related ticket #5234
- [x] Link to [Sketch file](https://share.goabstract.com/584e7002-4d07-4ce5-aafe-dc825e076a27?sha=f0b8ca1b588425d1ef83c57a9f4126c8ff97648e)
- [x] Design changes been merged into the master Sketch file
- [x] Desktop and mobile mockups are included
- [x] Assets are included - [icon](https://drive.google.com/drive/folders/1kPMOO9YoMybLN-MqziLUsmGE2EQ3hAVp?usp=sharing)
- [x] Hover state for elements are designed - no hover state
- [x] Other states for elements are designed (e.g., error state for form) - n/a

**Comment by jamilasnell** [comment]
https://redpen.io/p/yqece0a9215e9c33f1 

[#5234](https://github.com/mozilla/foundation.mozilla.org/issues/5234)

**Comment by mmmavis** [comment]
PR merged!
