### ISSUE TITLE
ArticlePage StreamField SCSS cleanup

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#5359]
### File(s) or components

ArticlePage template (`article_page.html`) and it's related StreamField blocks need CSS cleanup. This work is around #5075 

### Reason for cleanup

There are some inconsistencies around things like font size and line heights that need to be checked with a designer and frontend dev. 

### Tasks:
- [x] child-pages-children-title should just use .body style but with line height override 24px instead of 27px. Need to check with the designers to see if this override is really necessary.
- [x] Check with designer about font size and line height overwrides (ie. `@include set-text-size(16px, 24px);`)
- [x] Check with designer about font-weight: 300 in `.publication-notes .rich-text p` 
- [ ] Article Summary Bar  z-index needs to be increased so it doesn't get overlapped by the footer 
- [x] Don't use BEM styling for `publication-hero-container--small`
