### ISSUE TITLE
PNI - homepage - creep-o-face-o-location-o

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#5412]
**Tasks**
- [x] update the color of the speech bubble 
- [x] add in the styling tweaks to match new comps
- [x] update the location of the creep-o-meter content when search is active (see description below)
  - [x] mobile
  - [x] desktop
- [x] update the location of the creep-o-meter during scroll (see description below)
  - [x] mobile
  - [x] desktop
- [x] update initial creep-o-meter content to contain the intro text

**Desktop**
- [Creepy face appears center between search and checkbox with intro speech bubble](https://share.goabstract.com/e9fd07c9-605e-4ca9-b99c-7a3686de51cb?collectionLayerId=103e293c-16c0-48af-bac2-dc7d7545e5ea&mode=design)
- [When search is selected, search bar expands and creepy face relocates to bottom right corner ](https://share.goabstract.com/e9fd07c9-605e-4ca9-b99c-7a3686de51cb?collectionLayerId=6619f77a-a5e3-4019-b224-8adf02478629&mode=design) _(if search bar is closed creepy is center)_
- [If user is typing and creepy isn't determined yet, we can use a neutral smiley face with no speech bubble](https://share.goabstract.com/e9fd07c9-605e-4ca9-b99c-7a3686de51cb?collectionLayerId=a05bb884-48f2-47d3-b0ea-4ca413cd4212&mode=design)
- Faces change depending on how creepy the products are in viewport _(from not creepy to super creepy, see below)_
- Creepy face appears sticky up until last row of products (just after it so it doesn't block product thumbnail)

**Mobile**
- [Creepy face only appears center during initial presentation since search bar is open by default on mobile](https://share.goabstract.com/e9fd07c9-605e-4ca9-b99c-7a3686de51cb?collectionLayerId=3f690fff-c322-4f11-8505-04aee49fea04&mode=design)
- [As user scroll past intro creepy face, it relocates to bottom right corner of viewport](https://share.goabstract.com/e9fd07c9-605e-4ca9-b99c-7a3686de51cb?collectionLayerId=8d1fc7b3-fad0-4bdd-9815-6ef8ee18e5c8&mode=design)
- Creepy face appears sticky up until last row of products (just after it so it doesn't block product thumbnail)

---

###  Design -> Dev Handoff Checklist
(Feel free to remove items that are not applicable.)

- [x] Design has been finalized
- [x] Link to related ticket: #5314
- [x] Link to Abstract (make sure it can be viewed by anyone)
- [x] Design changes been merged into the master Sketch file
  - Merged into master Sketch file via Abstract. (_Master > Buyers Guide.sketch > [Home Page Updates (Q4 2020](https://share.goabstract.com/07a9aca5-3903-4f00-828a-6ac8bebb5be3?sha=e49d77cc9da6a70e8c412cd985e28138a3091cd5))_).
- [x] Desktop and mobile mockups are included
  - [[Desktop] Homepage - Index](https://share.goabstract.com/e9fd07c9-605e-4ca9-b99c-7a3686de51cb?collectionLayerId=103e293c-16c0-48af-bac2-dc7d7545e5ea&mode=design) _(initial presentation)_
  - [[Desktop] Homepage - Scroll ](https://share.goabstract.com/e9fd07c9-605e-4ca9-b99c-7a3686de51cb?collectionLayerId=44c49575-bd16-462d-a712-b76353238f92&mode=design)  _(sticky by bottom right corner of view port on scroll)_
  - [[Mobile] Homepage](https://share.goabstract.com/e9fd07c9-605e-4ca9-b99c-7a3686de51cb?collectionLayerId=3f690fff-c322-4f11-8505-04aee49fea04&mode=design)  _(initial presentation)_
  - [[Mobile] Homepage -  Scroll](https://share.goabstract.com/e9fd07c9-605e-4ca9-b99c-7a3686de51cb?collectionLayerId=8d1fc7b3-fad0-4bdd-9815-6ef8ee18e5c8&mode=design) (_sticky by bottom right corner of view port on scroll)_
- [x] Name of the Sketch file (and specific page/section to look at, if applies)
- [x] Assets are included. Link: https://drive.google.com/open?id=1AtHaj5YuXTQh03uDbz2JwZ6dPLxM3UiO&authuser=sabrina%40mozillafoundation.org&usp=drive_fs 
  - Note: bubbles preferably done purely in HTML / CSS so it is responsive
- [x] Other states for elements are designed: various face changes on scroll and all assets exported
<img width="933" alt="image" src="https://user-images.githubusercontent.com/2492510/96520842-cc430900-1224-11eb-8f69-3d3614d5df91.png">

**Comment by Pomax** [comment]
@sabrinang is this issue ready to be worked on?

**Comment by Pomax** [comment]
Placeholder for the speechbubble - we can probably do that in pure HTML:
```html
  <div class="info-box">
    <div class="bubble">
      Surely this isn't creepy! 
      <span class="pointer-bg">
        <span class="pointer-fg">
        </span>
      </span>
    </div>

    <div class="emoji"></div>
  </div>
```

```css
body {
  background: white;
}

.info-box {
  display: flex;
}

.emoji {
  background: #ffdd00;
  width: 60px;
  height: 60px;
  border-radius: 100%;
  margin-left: 10%;
}

.bubble {
  display: block;
  position: relative;
  padding: 1em;
  background: #d3d5fc;
  border-radius: 1em;
  width: 50%;
  font-family: Verdana;
}

.bubble .pointer-bg {
  position: absolute;
  display: block;
  top: 25%;
  right: -10%;
  width: 10%;
  height: 50%;
  background: #d3d5fc;
}
.bubble .pointer-fg {
  display: block;
  width: 100%;
  height: 100%;
  border-radius: 0 0 0 100%;
  background: white;
}
```

![image](https://user-images.githubusercontent.com/177243/96522048-76bc2b80-1227-11eb-92b4-fb698b85e4b1.png)

**Comment by Pomax** [comment]
we decided to reuse the code we already have in place, since it's already CSS+SVG based, but recolored to match the new comps

**Comment by KalobTaulien** [comment]
Closing this PR as it's been manually merged into #5558

**Comment by KalobTaulien** [comment]
Also want to give a big shout out to @hyshka for helping me solve a Firefox twitch when we use a fixed element inside of a sticky element. 🎉 Thank you!

**Comment by mmmavis** [comment]
PRs have been merged. Code cleanup is needed but will be tackled as followup. See https://github.com/mozilla/foundation.mozilla.org/issues/5575
