### ISSUE TITLE
[Publications] Import AI Whitepaper with Publications Template

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#5536]
[Here](https://docs.google.com/presentation/d/1fXFcilVTCgp4ngHSOA5Atm31eCQe2ocOkYKsrbkDhUg/edit#slide=id.g25275a8168_0_425) is some background on the design of the Publications template.

### Todo
- [x] Figure out where the whitepaper lives on foundation.mozilla.org - `.../insights/trustworthy-ai-whitepaper`
- [x] Get corresponding wagtail permissions
- [ ] [Import content](https://drive.google.com/file/d/1LD8pBC-cu7bkvU-9v-DZEyCmpWED7W7Z/view) or [doc is here if that's easier](https://docs.google.com/document/d/17HHH1RRXMmRzEO6JWaatAIFRSRhtAROtw_seTDnmFJk/edit)

**Comment by iamraghs** [comment]
i can solve this issue...

**Comment by kristinashu** [comment]
I believe the url will be /insights/IA-whitepaper (cc @taisdesouzalessa is that right?). I tested it on staging and publications template is available under /insights so once it's pushed to production then you should be able to add the content there.

**Comment by taisdesouzalessa** [comment]
@kristinashu the url is `/insights/trustworthy-ai-whitepaper`. I have a question though, in the [URL spreadsheet](https://docs.google.com/spreadsheets/d/184z7LnHIghXDp2NIns4T8zlpBDAdaRFuPMUDX7ijHYY/edit?usp=sharing) (cell C32) there was a talk about the Trustworthy AI research being more than the whitepaper (including a landscape analysis). Do you have more info on that, Kristina? I feel that since we don't have it now we can leave the URL as proposed (`/insights/trustworthy-ai-whitepaper`) and once the research expands we can then create a hub for it and the URL gets an extra level, as proposed on the cell D32 (`/insights/trustworthy-ai-research/[name-of-whitepaper]`) on the spreadsheet. What do you think?

**Comment by kristinashu** [comment]
Thanks @taisdesouzalessa! I think we should go with `/insights/trustworthy-ai-whitepaper`

**Comment by kristinashu** [comment]
I've started the very basic structure https://foundation.mozilla.org/en/insights/trustworthy-ai-whitepaper/ - mostly just to make sure I understand I know what's going on... So far so good!

**Comment by kristinashu** [comment]
I've opened a follow up ticket for a design to add graphics to the Publication once all the content has been entered https://github.com/mozilla/foundation.mozilla.org/issues/5681.

**Comment by kristinashu** [comment]
@jamilasnell this is done, right?

**Comment by jamilasnell** [comment]
Yes it is! I will close this
