### ISSUE TITLE
PNI search cleanup

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#5575]
File changes mostly in https://github.com/mozilla/foundation.mozilla.org/pull/5561

- [ ] Break this work down into smaller stories and add to Epic
- [ ] This code definitely needs a cleanup pass, and possibly a revisit to "do it right" rather than "make it workish".
- [x] set up html scaffolding so that the "hit area" for the search bar can be made to extend beyond the standard element bounding box (https://github.com/mozilla/foundation.mozilla.org/issues/7471 should solve this)

**Comment by jamilasnell** [comment]
This has been actioned on!
