### ISSUE TITLE
Create Network Personas

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#566]
- [x] 1. gather benchmarks - #568
- [x] 2. analyze the relationships between emerging personas from Story Engine, the [Enchilada doc](https://docs.google.com/document/d/13VHN6xazlMTWyuwMe_ivjwpy_CGLd8jGaOlKnLSFJJ0/edit?usp=sharing), Mark's [X-Plane deck](https://drive.google.com/a/mozilla.com/file/d/0B1dIaWlgfRdIVnM5Nm00OW9YVWc/view?usp=sharing), [Jesse's strategy](https://docs.google.com/a/mozilla.com/document/d/13waxxLxbfWo4qBI6ZsakEI1nXCBfA6ZTPnaMk3PIIPE/edit?usp=sharing) docs and Venetia's [Conscious Choosers](https://drive.google.com/a/mozilla.com/file/d/0B2wvfBjG7Mb1S1VKblFBVUlzRk0/view?usp=sharing) draft research - #587
- [x] 3. define draft persona groups. identify missing audience types - #635
- [x] 4. [cross-team research](https://github.com/mozilla/network/issues/566#issuecomment-316187474) gathering for the missing audience types that will emerge from analysis of item 2 #604
- [x] 5. review member interviews, write main points in sticky notes and do an affinity diagram per group - #570
- [x] 6. draft personas in a doc #714
- [x] 7. merge personas from doc if necessary 
- [x] 8. Draft Persona Cards (designed) #719 
- [x]  9. Copy review of personas doc  #801
- [x] 10. Place revised copy into personas' cards #919
- [x] 11. Personas draft: program staff review during All Hands #925
- [x] 12. Personas draft: post All Hands feedback (staff)  #945
- [x] 13. defining success #671
- [ ] 14. validate/ iterate over Personas
 
Full list with details [here](https://docs.google.com/a/mozilla.com/document/d/1hdiRv6l7P_oWPw7XvzO__F06WsrGUaoFrXkppkG2WQ4/edit?usp=sharing)

**Comment by taisdesouzalessa** [comment]
@xmatthewx I added 2 other checkboxes there that I felt were missing (items 5 and 6). We had a ticket for benchmark in the design repo that I'll move to the Network repo, ok?

**Comment by jessevondoom** [comment]
It may be underway but I'm adding a note to say it's worth talking to Paul Z and the insights team about people who aren't covered by StoryEngine — specifically activists, action-takers, and the more general supporters ring of the enchilada. I feel like we'll have a wealth of data around leaders, some robust thinking about activists and action takers, and a whole lot less when it comes to supporters...who probably map to some of the MoCo research on conscious choosers but also aren't exactly the same.

**Comment by taisdesouzalessa** [comment]
@jessevondoom - based on our conversation from yesterday (correct me if I am wrong), I should first focus on the relationships between Story Engine and other docs we have (like Enchilada and others), correct? This should be my deliverable for this heartbeat. I could also (in this heartbeat) dig in one group of persona (like Hive members, for instance) to have a model draft (as Kristina suggested) so @kristinashu and @flukeout can see the model from Story Engine in order to define the shape of the deliverable. Plus this draft can receive feedback from others which will inform the other personas. Does that sound ok to you? @xmatthewx @hannahkane Jesse?

**Comment by xmatthewx** [comment]
That sounds good to me. It definitely makes sense to map the strategy as a lens to define the audience. I also like your idea Taís of pursuing one persona to keep the work grounded and moving. 

@taisdesouzalessa - do you want an intro to Paul Z? He'd be a great partner along with Christine P in mapping out the groups. 

One side note: I think we should pursue personas groups decoupled from specific program groups. Rather than Hive members, we'd consider Web literacy teachers/professionals. Does this ring as true?

**Comment by jessevondoom** [comment]
I think @xmatthewx's suggestions about decoupling the personas is an important point. I'd go a step further and think the abstraction might want to involve some level of the leader/activist/supporter language as well — so what patterns hold true for all people in the web literacy space, and what are the differences between a leader in that space and someone early/mid career growth? 

Not sure how this looks in execution but I'm guessing that working on a specific persona group from Storyengine mixed with exploring a mapping between enchilada doc user types, conscious choosers, and our real-world examples will lead you to a more solid idea of what that framework could look like.

**Comment by hannahkane** [comment]
+1 to all of the above

**Comment by taisdesouzalessa** [comment]
Thanks for the insights here, team! I'll follow the directions. I'll spend some time reading all those things and coming up with relationships/insights. 

For now, I am quickly scanning each one of the interviews to understand better the relationship of each person with Mozilla so I can relate the info to the Enchilada doc.

Here is the spreadsheet I am building/using: https://docs.google.com/a/mozilla.com/spreadsheets/d/18T_uclwqj-c5_FDhw2sgppnaskHurI7r2IPiD3WN8Rw/edit?usp=sharing
I'll keep you posted and I have some progress.

@xmatthewx I know Paul Z. and I think he would be a great partner as well, he knows a lot about the network. Once I have all these data a bit more consolidated in a meaningful format, I would like to get him involved as well, how does that sound? I thought about Sam B too since she led lots of Network sessions during All Hands. Should we keep them both in the loop once I have somethign mroe concrete to show?

**Comment by taisdesouzalessa** [comment]
@xmatthewx @hannahkane @jessevondoom I feel I should have done this earlier...I apologize the delay. I did this diagram to show the step-by-step process I am using to create personas from Story Engine. I think it is important I show you what I have been doing so we are all on the same page and also to align the expectations. The label feedback was placed at points in which I think it would be valuable to have input.

I would like to highlight that at the end of this project we will have only personas that are represented in the Story Engine. We will need to discuss next steps if it is expected that we have more than what is covered in StoryEngine. 

Please let me know if all of this sounds good to you!

<img width="383" alt="image" src="https://user-images.githubusercontent.com/22157921/28944206-8b00873a-7856-11e7-8bf5-7ea3ae37eeea.png">

Link to the chart: https://invis.io/GKCW2TTBY#/247038970_Process-Personas-Storyengine-Diagram

**Comment by jessevondoom** [comment]
I think the process looks great. I am a little concerned that we're limiting ourselves to StoryEngine, but understand that as a starting point. When we do want to expand outward, should we think about doing the StoryEngine process with people as a starting point or is their some kind of lesser data collection / interview process we could use? (StoryEngine Lite™)

**Comment by xmatthewx** [comment]
Nice process @taisdesouzalessa, thanks for sharing.

I'd hope that we can create some placeholder Personas to fill the gaps. If we evolve my [proposed groups](https://docs.google.com/document/d/1rJJOC_qvFulL9sFlhs02MXRSpCQRoAGaXg6PISvFA60/edit#heading=h.3q116stei8hs) to something that feels right we can find a lighter way to collect data. Christine also seems keen to go out and find the missing people for another round of interviews.

**Comment by xmatthewx** [comment]
@taisdesouzalessa - I think we need an issue for Item 3 at top of this issue. Can link to the brainstorm doc. Might also be good to have a single google drive folder to gather all these docs. I can make ya a mzl.la link.

**Comment by taisdesouzalessa** [comment]
Thanks for the insights here, @xmatthewx and @jessevondoom. I think it would be great if Christine could interview the missing people so we can fill in the gaps (that would be the ideal way I think). 

I don't know how long this process (the new interviews for StoryEngine) would take but if we need something sooner and lightweight an idea would be to use proto-personas. What I mean by that is that we could do some sessions with staff and build those missing personas based on their knowledge rather than user research. Then, once we have the user research from Christine, we improve those personas, validating or erasing assumptions we made with the proto ones. 

Wondering what you think of that idea, Matthew. I think this process would be a way to evolve your proposed groups for the areas we don't have StoryEngine yet. Let me know if you had other ideas in mind.

**Comment by taisdesouzalessa** [comment]
This process created lots of questions on my mind: in terms of where we are, where we are going, what is included in the Strawperson doc vs Enchilada...

I was wondering if you could help me with that? I did a diagram as an attempt to have a birds-eye view (I apologize for my obsession for diagrams...haha but they help me to think in systems). Could you please take a look and add comments to InVision? Please start with the dot in the yellow area, close to "Leaders", then hit next - it is a guided tour. 

https://invis.io/PECWSR4A3#/247259951_Overview-Personas

Let me know if it makes sense to you or if I am getting something wrong. I am trying to set a roadmap so I know where I am going.

**Comment by taisdesouzalessa** [comment]
> I think we need an issue for Item 3 at top of this issue.


@xmatthewx I created a issue for that: #635. Feel free to edit it if you think it is missing something.

> Might also be good to have a single google drive folder to gather all these docs. 

Good call, I will do that


> I can make ya a mzl.la link

I don't understand what you mean by that :(. A link for the Google Drive folder?

**Comment by xmatthewx** [comment]
Added comments in Overview-Personas. Hit me up on slack with any questions. Also, I can give you a link like mzl.la/mofo-persona-docs, so we can all easily find these docs. Could be a google drive folder or an etherpad.

**Comment by taisdesouzalessa** [comment]
Thanks, Matthew! I would love an official link...yay. A Google Drive folder would work the best so I can store not only text but also images of diagrams for easy access. Once I am back my top priority will be organize all these files and put them in one place.

**Comment by taisdesouzalessa** [comment]
@xmatthewx - I added 2 more items on this list (items 9 and 10) to reflect the current state of the process.

**Comment by kristinashu** [comment]
Assigning to @beccaklam to review then close and open a new summary ticket in the [Design repo](https://github.com/MozillaFoundation/Design/issues).

**Comment by beccaklam** [comment]
Closing this ticket for now. Summary ticket [here](https://github.com/MozillaFoundation/Design/issues/307).
