### ISSUE TITLE
QA the pni-as-wagtail branch

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#5777]
Surfaced tasks

- [x] ~meets_minimum_security_standard field is not rendering correctly in the product template. `no` ends up rendering as `unknown`~
  - ~PR for updating the `yes_no` tag to better understand the values it has to deal with: https://github.com/mozilla/foundation.mozilla.org/pull/5834~ landed
- ~[x] finish adding all the fields that need translations: https://github.com/mozilla/foundation.mozilla.org/pull/5829~ landed
- [x] ~products don't link to the correct url (should not include `/product/`): https://github.com/mozilla/foundation.mozilla.org/pull/5838~ landed
- [x] ~mobile-size nav does not preselect "all" - https://github.com/mozilla/foundation.mozilla.org/pull/5843~ landed
- [x] ~improve timing for the various pages: https://github.com/mozilla/foundation.mozilla.org/pull/5850~ landed
- [x] ~"related products" seem to be missing the privacy ding icon: https://github.com/mozilla/foundation.mozilla.org/pull/5852~ landed
- [x] ~speed up page load by reducing queries caused by `.specific` https://github.com/mozilla/foundation.mozilla.org/pull/5833~ landed
- [x] ~speed up page load by refactoring is_current out of existence: https://github.com/mozilla/foundation.mozilla.org/pull/5853~

Deferred tasks:
- [ ] category pages seem to have `privacynotincluded` hardcoded as destination (so testing with `privacynotincluded-new` and clicking on a category moves folks to the old page) - filed https://github.com/mozilla/foundation.mozilla.org/issues/5870
- [ ] find a new home for the button that clears the Django cache - filed https://github.com/mozilla/foundation.mozilla.org/issues/5871
- [ ] create an access group for people who are allowed to create/edit PNI products - filed https://github.com/mozilla/foundation.mozilla.org/issues/5872
- [ ] consider changing the routing logic, with products being children of a separate PNI homepage, with the `@route` logic housed in that homepage class instead of in the ProductPage - filed https://github.com/mozilla/foundation.mozilla.org/issues/5873

### Staging test URLs:

- current PNI: https://foundation.mofostaging.net/en/privacynotincluded
- new PNI: https://foundation.mofostaging.net/en/privacynotincluded-new

### notes
- comments are not enabled on staging, so those won't show up
- related products and privacy links were previously unordered, so the data should be the same but the ordering will almost certainly be different.

---

We have a hard deadline where the code needs to be up on prod by the end of Thursday. So:

- defer working on the following parts, so we can land the "real" part ASAP :
  - load_fake_data
    - [ ] add images to product page factory - filed https://github.com/mozilla/foundation.mozilla.org/issues/5874
    - [ ] add categories to product page factory - filed https://github.com/mozilla/foundation.mozilla.org/issues/5875
  - percy-specific testing data - filed https://github.com/mozilla/foundation.mozilla.org/issues/5876
    - [ ] percy-specific general product
    - [ ] percy-specific software product
  - parity unit testing between old PNI and new PNI - filed https://github.com/mozilla/foundation.mozilla.org/issues/5877

- instead:
  - [x] add all the fields that need localization to translation.py
  - [x] ensure that the CMS admin view is (as far as possible) the same between old and new PNI
  - [x] ensure that votes are the same between old and new
    - [x] ensure voting works.

If they do, merge this in, and do reliability testing on staging.

- [x] verify that `manage migrate_products` works
  - This works, but it's a slow process

Once stage testing is considered good enough, we'll have to update the code so that it generates `privacynotincluded` rather than `privacynotincluded-new`, and then push that through to prod. Then after that's done, we can push an update that turns off the `networkapi.buyersguide` url patterns so that wagtail becomes solely responsible for serving the data.

Then we get to immediately follow up with code clean up because this landed earlier than it should have.

**Comment by Pomax** [comment]
change of plans: we have a hard deadline where the code needs to be up on prod by the end of Thursday. So:

- defer working on the following parts, so we can land the "real" part ASAP :
  - load_fake_data
  - CI-specific testing data
  - additional parity unit testing
- instead, verify that all fields on prod get converted properly during `manage migrate_products`
  - voting should work, so that's no longer a concern

If they do, merge this in, and do reliability testing on staging.


figure out what _needs_ to be fixed for things to work well enough to flip the switch, and what can be deferred even if it means immediate follow-up, e.g. load_fake_data and CI related testing is now basically irrelevant, the only thing that matters is that the original data gets correctly converted

**Comment by Pomax** [comment]
Not noticable for products with enough votes already, but for products with only a handful of votes: it looks like we're showing the on-page voting result based on the votes "at the time of page loading" (which makes sense, we used to not update votes in real time), so you can get things like this:
![image](https://user-images.githubusercontent.com/177243/101683621-0ad19480-3a1a-11eb-9091-43a6d0a98284.png)

Obviously, 5 votes don't turn into 25% + 25% + 50% - the vote result is based on 4 votes and already know at the time of page-loading, so the voting JS will need to be updated to take the cast vote into account.

**Comment by Pomax** [comment]
products loaded on `privacynotincluded-new` have a nav that points to `privacynotincluded` links instead. This would not be noticed if the route is named the same, but it suggests a code incompletion for the products navbar

**Comment by Pomax** [comment]
The cache clearing button for PNI data should find a better home now that we won't be using the snippet menu anymore. It currently lives here:

![image](https://user-images.githubusercontent.com/177243/101709326-16d24c00-3a44-11eb-84e5-65ee4ea565bc.png)

And that's not the right place if products now live under a real page.

/cc @KalobTaulien

**Comment by TheoChevalier** [comment]
Minor visual regression in footer (icons misaligned)
![Screenshot_2020-12-10  Privacy Not Included A Buyer’s Guide for Connected Products(1)](https://user-images.githubusercontent.com/1294206/101777764-da0d6000-3aea-11eb-9c62-f35ef4264589.png)

**Comment by kristinashu** [comment]
One potentially important issue is with the Minimum Security Standards.

On prod it says "No" https://foundation.mozilla.org/en/privacynotincluded/products/kidkraft-amazon-alexa-2-in-1-kitchen-market/
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/1068783/101808111-c520d480-3aca-11eb-9faf-99f98b8521b8.png">

But on the new site it says "Unknown" https://foundation.mofostaging.net/en/privacynotincluded-new/kidkraft-amazon-alexa-2-in-1-kitchen-market/
<img width="1052" alt="image" src="https://user-images.githubusercontent.com/1068783/101808136-cce07900-3aca-11eb-80de-c6c0eaea151f.png">

I checked with Jen and she says she hasn't updated it recently. I'm trying to find other product were this is happening but haven't found any yet... @Pomax @KalobTaulien are you able to double check the code to see if there's possibly an issue here?

**Comment by Pomax** [comment]
@TheoChevalier looks like this is not so much a regression as "this is also true on https://foundation.mozilla.org/en/privacynotincluded/" so I'll file a separate issue for that.

@kristinashu good find, I will investigate what's going on with that.

**Comment by kristinashu** [comment]
Noting a couple differences that appear on PNI staging vs PNI-new staging vs PNI prod.

NOT A BLOCKER - the order of the privacy policies is reversed when there are multiple.

<img width="899" alt="image" src="https://user-images.githubusercontent.com/1068783/101811384-dff54800-3ace-11eb-9c60-90216b64a4ff.png">
vs
<img width="907" alt="image" src="https://user-images.githubusercontent.com/1068783/101811444-f3081800-3ace-11eb-9c40-eab3d4a2bc22.png">

Product name is missing on the **regular PNI staging** landing page https://foundation.mofostaging.net/en/privacynotincluded/ but is good on **PNI-new** staging vs **PNI prod**.
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/1068783/101811587-1e8b0280-3acf-11eb-9b90-cf24e470b574.png">

**Comment by Pomax** [comment]
categories load agonizingly slow.

**Comment by kristinashu** [comment]
When on a product page at a narrow screen width, the word "All" should be visible in the dropdown nav.

Screen cap from -new
<img width="608" alt="image" src="https://user-images.githubusercontent.com/1068783/101829526-ffe53580-3ae7-11eb-93aa-f8053066f358.png">

Screen cap from prod
<img width="607" alt="image" src="https://user-images.githubusercontent.com/1068783/101829612-1e4b3100-3ae8-11eb-8038-994754a14c52.png">

**Comment by kristinashu** [comment]
> categories load agonizingly slow?

Agree. It is unbearably slow. If it's going to be that slow on prod then I would say it's a blocker for launch. I do not feel comfortable launching with that slow of a load time.

**Comment by Pomax** [comment]
same. I'll spend today investigating why it's so slow.

**Comment by sabrinang** [comment]
Comparing https://foundation.mofostaging.net/en/privacynotincluded-new/ to https://foundation.mozilla.org/en/privacynotincluded

**Product Pages**
- Missing comments
- Related products: ding symbol inconsistently present on thumbnail, order shuffled 
<img width="1396" alt="image" src="https://user-images.githubusercontent.com/2492510/101842091-2b721b00-3afc-11eb-82ce-e0a78cde560e.png">
example: /kano-coding-kits
<img width="1406" alt="image" src="https://user-images.githubusercontent.com/2492510/101842123-39c03700-3afc-11eb-8d91-6e06e02d3dc1.png">
example: /amazon-halo

**Comment by Pomax** [comment]
- Staging does not load comments, so that's expected.
- The related product ordering is due to how the new code works so the same products will show but their ordering is not guaranteed the same (old code did not technically have an ordering)
- the missing ding in related product definitely needs investigating.

**Comment by Pomax** [comment]
I suspect the missing title on "old" PNI on staging is a typo in the template from when we accidentally tried to update the existing templates instead of creating updated copies so we could still have the old data render properly.

**Comment by Pomax** [comment]
we can close this after filing followup issues for each deferred task

**Comment by Pomax** [comment]
all open issues have been filed as follow-up work tied together in an epic https://github.com/mozilla/foundation.mozilla.org/issues/5878
