### ISSUE TITLE
Wagtail PNI pre-flight checklist

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#5841]
# stage testing

- [x] land code to staging
- [x] run migration script against staging db
- [x] QA and identify any issue that needs fixing prior to launch using `privacynotincluded-new` url - see https://github.com/mozilla/foundation.mozilla.org/issues/5777
  - [x] fix immediate issues, file-for-followup anything that isn't critical

# prod push

- [x] promote staging to production
- [x] run migration script against production db

# flipping the switch

- [x] last chance QA on the live site using `privacynotincluded-new` url
- [x] localize all fields that need it
- [x] rename `privacynotincluded-new` to `privacynotincluded` (this will **not** change old PNI over to new PNI, but sets up a seemless switch in the next step)
- [x] create PR that turns off the old hardcoded PNI urls from `networkapi/buyersguide/urls.py`, and push that through to prod
  - [x] push to staging
  - [x] push to prod - **this flips the switch**

**Comment by Pomax** [comment]
this. is done.
