### ISSUE TITLE
Platform policy tracker microsite

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#6225]
via Jon: We would like to house the entire platform policy tracker project (tracker doc, interactive graphic, and blog posts) in one single place. Which template can we use, and are we able to get any design assistance?

Still waiting for content but it would included
- Series of blog posts ([rough outline](https://docs.google.com/document/d/1Dzb3Hw3TDL9gz_REfTzhHw7duc8AGA5QU-5QJkmOClw/edit))
- Link to Platform tracker [doc](https://docs.google.com/document/d/1-b5b_AgJhz7rAXaSpekwBwZWHx_A7iSleoOGxK0lZto/edit) (maybe move this to the publication template)
- Embedded graphs (implementation happening in - Interim interactive graphic host and embed in iframe #6223

Todo
- [x] Determine URL
- [x] Determine template type
- [x] Crop graphic from [doc](https://docs.google.com/document/d/1-b5b_AgJhz7rAXaSpekwBwZWHx_A7iSleoOGxK0lZto/edit)
- [ ] Gather content
- [ ] Determine subnav (if needed)
- [x] Determine and add blog tag
- [x] Add Recent Blog component
- [ ] Consider moving doc to publication template

**Comment by kristinashu** [comment]
Will repurpose this original page https://foundation.mozilla.org/en/campaigns/election-policy-tracker/

I expect we'll need to create three new thumbnail graphics for the blog posts but I think that's it. It is now on the advocacy team to update the content on the hub page. Blog posts need to be tagged with "platform policy tracker" to appear on the hub page.

**Comment by kristinashu** [comment]
Project brief is [here](https://docs.google.com/document/d/1xWfqWyeZVeRWdzdlh6ZFkTHv5QOglYG-DKtgUWd5yLM/edit#).

New test page is [here](https://foundation.mozilla.org/en/campaigns/election-integrity-and-platform-accountability/).

**Comment by kristinashu** [comment]
Going with this direction https://foundation.mozilla.org/en/campaigns/election-integrity-and-platform-accountability-v2/

Kaili/Jon will update it with intro text and Nat will create the graphics.
