### ISSUE TITLE
Pre-launch checklist of platform tracker

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#6301]
Hub https://foundation.mozilla.org/en/campaigns/election-integrity-and-platform-accountability
- [x] Remove password 
- [x] Update copy (intro text, title for blog posts, share text under the promote tab) (Jon/Kaili)
- [x] Make sure "Recent blog entries" component is using the tag "platform policy tracker" so they appear on this page
- [x] Update banner image
- [x] Update share graphic

Each post
- [x] Add tag "platform policy tracker" to all posts that should appear on the hub page
- [x] Add embedded graph to blog 1 (@benhohner https://github.com/mozilla/foundation.mozilla.org/issues/6223)
- [x] Add share image ([wip](https://github.com/MozillaFoundation/Design/issues/777))
- [x] Remove password

**Comment by benhohner** [comment]
@kristinashu Do we need to do anything else on our end for this? When's the launch date?

**Comment by kristinashu** [comment]
Nothing else that I am aware of. Also not sure about the launch date. From our conversations it sounded like between Mar 3-10. cc @jamilasnell do you have any additional insights?

**Comment by kristinashu** [comment]
Pinged Kaili, they're removing the passwords now so it is all live now.
