### ISSUE TITLE
[epic] PNI optimizations

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#6410]
After extensive testing, in order to have a sequence of events we can action on, we've come up with the following plan of attack:

- [x] land the code that reduces the number of thumbnails on that PNI catalog pages from 8x to 2x per product
- [x] land the "simple caching" (but category/locale aware) so the reduced PNI homepage/category pages are sped up a bit
- [x] turn off cloudinary on prod because the PNI homepage should now at least no longer time out, and get cached after principal loading
- [x] remove just enough of the BG app to be guaranteed of the fact that it's no longer using old views anymore
  - [x] fix all the tests this breaks
- [x] replace the `image` template tag with the deferred rendition `image_url` tag 
  - [x] fix all the tests _that_ breaks, which should be zero, but that's what we thought before, too and instead ended up with this issue.
