### ISSUE TITLE
[Epic] Update streamfield blocks to always be distinct rows

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#6517]
[Google Doc Initial Pseudo Code thoughts here](https://docs.google.com/document/d/1ATrUOaUMzPL9F1X9pkw--eRdhhsY75SeIHBo_Cu2EDU/edit)

## The goal: 
To make streamfield templates easier to maintain moving forward as more and more templates tend to break out of the existing grid. 

We don't want to be trying to break out of the grid for a wide stream block template, instead each stream block template should be it's own bootstrap row. 

## The problem:
Blog and Article page stream block templates are used on both page types, but have different widths. I believe the blog is a `.col-8` and the article pages are a `.col-10` base grid.

## The ideal solution:
Ideally we would have an easy-to-maintain way of managing blocks from a higher level without editors needing to click "wide" or add a column wide on each page type (or parent page) so their editing experience remains the same as it always has been, but the code becomes easier to maintain moving forward. Example using SCSS:

```
#view-blog .video-block {
  @extend .col-12
  @extend .no-gutters
}
#view-publications .video-block {
  @extend .col-10
}
```

## What we need to audit/discover 
- [ ] Which primary templates possibly need some adjusting. For example, the blog index page may be setting a .col-8 for all streamfield blocks. We would need to widen that so the streamblock template widths can be handled using scss.
  - [ ] We may need the same audit on the article page. 
  - [ ] Will changing the template values affect any other page (ie. if the blog index page is using the module_page.html template, what else will that affect?
- [ ] Which stream blocks are being used on the BlogPage and ArticlePage. 
  - [ ] Are there any blocks that are being used on other pages? If if we change the template, for example, on a streamblock for the BlogPage, will it affect any other pages that we aren't expecting? 
- [ ] Explore options (possibly with the design team) about what to do with social icons that float down the page (if anything). 

## What we need to explore
- [ ] PoC with the SCSS solution to see if this is viable
- [ ] What a viable switch-over planning will be given an intent to update all streamfield blocks.

## Note:
Make sure we add a follow up ticket for this work to actually be completed.

**Comment by KalobTaulien** [comment]
This could end up being quite a bit chunk of work. And this ticket would be a good candidate for a post-spike / proof of concept ticket. 

We also need to assign someone to do this spike during tomorrows sprint planning.

**Comment by Pomax** [comment]
I've dropped some findings into the PoC issue that @danielfmiranda has on his plate

**Comment by danielfmiranda** [comment]
Closing this issue as we have completed all steps in the epic! 🎉
