### ISSUE TITLE
SPIKE: Explore and come up with a task list for actionable steps we need to implement wagtail-localize

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#6671]
Spike only. Future tickets to come from this. 

Helpful resources:
* https://docs.wagtail.io/en/stable/advanced_topics/i18n.html
* https://www.wagtail-localize.org/

### Steps needed to [re]implement wagtail-localize 

- [ ] We need a dedicated pipeline for testing the work. @tomusher we'll need your help with this. 
  - [ ] Needs CI setup to help us merge the main review branch into master later with no problems. 
- [ ] Remove model translation entirely before adding wagtail
  - [ ] Remove translation files
  - [ ] Remove requirement dependencies 
  - [ ] Remove tests 
  - [ ] Remove factory code that uses model translation 
  - [ ] Look for `thing_en=` in the source code and remove the `_en` 
  - [ ] Run tests to make sure everything passes
  - [ ] Merge into our review branch and let CI run for higher future-merge confidence
- [ ] We _really_ should, but don't have to, upgrade to Wagtail 2.13 and Django 3.2 before adding wagtail-localize. I think the last dry run I did up to Wagtail 2.13rc1 required me to do some model-translation work. 
  - [ ] Upgrade Wagtail to 2.12.* and upgrade Django to 3.0.*
  - [ ] Upgrade Wagtail to 2.13 and upgrade Django to 3.2.* 
- [ ] Add in wagtail-localize. Enable it in the settings, but don't do anything else with it yet. Let's take this in small steps. 
  - [ ] Make sure tests pass. 
  - [ ] Add in wagtail-localize into the requirement dependencies 
  - [ ] Merge into review branch and let CI run for higher future-merge confidence
- [ ] List out which fields should be TranslatableField and which fields should be SynchronizedField. @TheoChevalier we can really use your help here. A list of models/pages with which fields should be Translatable Vs Synchronized would be a life saver for implementation.
- [ ] Create migrations for all snippets. [This document](https://docs.wagtail.io/en/stable/advanced_topics/i18n.html#making-snippets-with-existing-data-translatable) will be _very_ helpful. We need to bootstrap migrations for each model. 
  - [ ] Make sure all snippet models are translated. 
  - [ ] Make sure all snippet fields have `translatable_fields = [ .. ]` set on them 
  - [ ] Make sure tests still pass. May need to do some adjusting for new language headers in the `request` object, particularly around redirects. 
  - [ ] Whoever integrates this, please confirm with Theo all the fields are set properly. 
- [ ] Tests ticket: 
  - [ ] We might end up at a point where we need to work on _just_ tests for a while. I recall some of these being rather tricky. First up: Make sure cypress tests for redirects work.
  - [ ] Make sure redirect tests continue to redirect to the appropriate language 
- [ ] Change the language picker in the footer of the website to properly set the language of the site 
- [ ] Add in pontoon integration. @pomax you and Karl may need to work on this together. 
- [ ] Documentation:
  - [ ] Write documentation on how to implement and support pontoon with any gotchas documented as well. Might be useful to put this in the wagtail-localize.org docs. 
  - [ ] We said we'd write docs for moving away from wagtail-modeltranslation and contribute it back to wagtail-localize. Lets write documentation on how we moved away from wagtail-modeltranslation to wagtail-localize, and commit the changes [to the wagtail-localize docs](https://www.wagtail-localize.org/how-to/migrate/wagtail-modeltranslation/)

### Post deploy steps:
- [ ] Create new locales in the settings 
- [ ] Synch all pages with 1/3rd of the new locales in the Wagtail admin. Do this 3 times so we don't hit timeout limits in heroku. We have quite a few pages and snippets, and want to make sure we don't run into any hiccups in production. 
- [ ] Start translating content (Theo) 

### Things we'll need to secure before getting started:
- [ ] Time from Pomax for code review. 
- [ ] Possibly Karl for Pontoon integration support
- [ ] Tom Usher for Devops setup
- [ ] Theo for translation support
- [ ] Kalob for doing the work

### Helpful code snippets for future reference:

```python
from wagtail_localize.fields import TranslatableField, SynchronizedField
class Model(Page):
    translatable_fields = [
        TranslatableField('title'),
        SynchronisedField('slug'),
        ...
    ]
```

**Comment by KalobTaulien** [comment]
Moving this spike into Review from @Pomax and @benhohner 

For an "Estimate" I would definitely suggest a full sprint for this

**Comment by benhohner** [comment]
Looks good. Let's create an epic. We can definitely arrange for you and Pomax to have a full sprint for this.
1. Do you think it's worth upgrading fo'mo to Django 3.2 first (possibly this sprint), before we do any localize work? 
2. @TheoChevalier can you please create a spreadsheet of the models that need to be upgraded and whether each field needs to be Translatable, Synchronized, or ignored before the next sprint?

**Comment by KalobTaulien** [comment]
Hey @benhohner 

Thanks for reviewing this! I'll make an epic out of this today. 

We should definitely upgrade Django and Wagtail first. That'll make things a bit easier for us I suspect.
