### ISSUE TITLE
Wagtail Localization

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#6703]
Epic for **Wagtail Localization**. The spike ticket can be found at #6671

All the below tasks are split into tickets in this epic, with the step number in the title so we don't get too far ahead of ourselves and need to spend time backtracking. 

The localization branch we're using in this repo is the `wagtail-localize-2021` [branch](https://github.com/mozilla/foundation.mozilla.org/tree/wagtail-localize-2021). **Note**: Please keep the original `wagtail-localize` branch as it has code we may want to reference in there while we work on localization. 

Helpful resources:
* https://docs.wagtail.io/en/stable/advanced_topics/i18n.html
* https://www.wagtail-localize.org/

### Steps needed to [re]implement wagtail-localize 

- [x] #6702  We _really_ should, but don't have to, upgrade to Wagtail 2.13 and Django 3.2 before adding wagtail-localize. I think the last dry run I did up to Wagtail 2.13rc1 required me to do some model-translation work. 
  - [ ] Upgrade Wagtail to 2.12.* and upgrade Django to 3.0.*
  - [ ] Upgrade Wagtail to 2.13 and upgrade Django to 3.2.* 
- [x] #6704 We need a dedicated pipeline for testing the work. @tomusher we'll need your help with this. 
  - [ ] Needs CI setup to help us merge the main review branch into master later with no problems. 
- [x] #6705 Remove model translation entirely before adding wagtail
  - [x] Remove translation files
  - [x] Remove requirement dependencies 
  - [x] Remove tests 
  - [x] Remove factory code that uses model translation 
  - [x] Look for `thing_en=` in the source code and remove the `_en` 
  - [x] Run tests to make sure everything passes
  - [x] Merge into our review branch and let CI run for higher future-merge confidence
- [x] #6706 Add in wagtail-localize. Enable it in the settings, but don't do anything else with it yet. Let's take this in small steps. 
  - [x] Make sure tests pass. 
  - [x] Add in wagtail-localize into the requirement dependencies 
  - [x] Merge into review branch and let CI run for higher future-merge confidence
- [x] #6707 List out which fields should be TranslatableField and which fields should be SynchronizedField. @TheoChevalier we can really use your help here. A list of models/pages with which fields should be Translatable Vs Synchronized would be a life saver for implementation.
- [x] #6708 Create migrations for all snippets. [This document](https://docs.wagtail.io/en/stable/advanced_topics/i18n.html#making-snippets-with-existing-data-translatable) will be _very_ helpful. We need to bootstrap migrations for each model. 
  - [x] Make sure all snippet models are translated. 
  - [x] Make sure all snippet fields have `translatable_fields = [ .. ]` set on them 
  - [x] Make sure tests still pass. May need to do some adjusting for new language headers in the `request` object, particularly around redirects. 
  - [x] Whoever integrates this, please confirm with Theo all the fields are set properly. 
- [x] #6760 Check that PNI localization works and adjust categories if needed. 
- [x] #6709 Tests ticket: 
  - [x] We might end up at a point where we need to work on _just_ tests for a while. I recall some of these being rather tricky. First up: Make sure cypress tests for redirects work.
  - [x] Make sure redirect tests continue to redirect to the appropriate language 
- [x] #6710 Change the language picker in the footer of the website to properly set the language of the site 
- [x] #6711 Add in pontoon integration. @pomax you and Karl may need to work on this together. 
- [ ] #6712 Documentation:
  - [ ] Write documentation on how to implement and support pontoon with any gotchas documented as well. Might be useful to put this in the wagtail-localize.org docs. 
  - [ ] We said we'd write docs for moving away from wagtail-modeltranslation and contribute it back to wagtail-localize. Lets write documentation on how we moved away from wagtail-modeltranslation to wagtail-localize, and commit the changes [to the wagtail-localize docs](https://www.wagtail-localize.org/how-to/migrate/wagtail-modeltranslation/)

## TRACKING DEPLOYMENT ISSUES

Use https://github.com/mozilla/foundation.mozilla.org/issues/7233 to report any issues you find while we're stage testing.

### Merge requirements

- [x] make sure `wagtail-localize-2021` is up to date with current master
- run through https://www.wagtail-localize.org/how-to/integrations/pontoon for staging:
  - [x] Generate an SSH keypair for Wagtail Localize (see vault)
  - [x] Add the public key (wagtail-localize-key.pub) as a deploy key for the l10n repo
  - [x] Add the SSH private key as BASE64-encoded heroku env var
  - [x] Configure the wagtail-localize-git plugin vars ([see docs](https://www.wagtail-localize.org/how-to/integrations/pontoon/#configure-the-wagtail-localize-git-plugin))
- [x] merge `wagtail-localize-2021` into master
- [x] verify staging works as expected
  - use https://github.com/mozilla/foundation.mozilla.org/issues/7233 for issues found during testing.
- [x] create sync locale "cron job" using heroku scheduler

## Pre-deploy steps

- run through https://www.wagtail-localize.org/how-to/integrations/pontoon for prod:
  - [x] Generate an SSH keypair for Wagtail Production (see vault)
  - [x] Add the public key (wagtail-localize-key.pub) as a deploy key for the l10n repo
  - [x] Add the SSH private key as BASE64-encoded heroku env var
  - [x] Configure the wagtail-localize-git plugin vars
- [x] send out notification to staff
- [x] create an explicit database snapshot for emergency rollsbacks
- [x] promote staging to production

### Post deploy steps (#6713)

- [x] Create new locales in the settings
- [x] Run sync_locale_trees
- [x] create sync locale "cron job" using heroku scheduler
- [x] Start translating content (Theo)!
- [ ] finalize this epic by tearing down the `foundation-localize` heroku app

### Things we'll need to secure before getting started:

- [x] Time from Pomax for code review. 
- [x] Possibly Karl for Pontoon integration support
- [x] Tom Usher for Devops setup
- [x] Theo for translation support
- [x] Kalob for doing the work

### Helpful code snippets for future reference:

```python
from wagtail_localize.fields import TranslatableField, SynchronizedField
class Model(Page):
    translatable_fields = [
        TranslatableField('title'),
        SynchronisedField('slug'),
        ...
    ]
```

**Comment by Pomax** [comment]
this epic was closed out long ago, any outstanding work should be new issues.
