### ISSUE TITLE
Improve newsletter sign-up text

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#6831]
Will has identified and requested that we improve the sign-up text in our newsletter sections to include more specific asks.

### Links
[Airtable link is here](https://airtable.com/tbljPmOCkK9JShaTS/viw9sdUJiIjCYpn0Y/recV78f369QS1vLPW?blocks=hide)

---

For now we're just doing a quick fix of updating the text to what Will has suggested:

> Help shape the future of the web for the public good. 

> Join our Mozilla News email list to get action alerts & internet tips right to your inbox.

### Todo
- [x] Identify all the places on the site where it would need to be updates
- [x] Make sure new copy will work
- [x] Give Theo a heads up that this is coming
- [x] Ping design for QA of PR
- [ ] Ping design once on prod (including updated CMS editable pages)
- [ ] Have this text translated by Theo
- [ ] Let stakeholders know it's done

**Comment by jamilasnell** [comment]
Just want to confirm @kristinashu that this is the final text:

    Help shape the future of the web for the public good.

    Join our Mozilla News email list to get action alerts & internet tips right to your inbox.

**Comment by kristinashu** [comment]
Yup, as far as I know that's what Will requested https://airtable.com/tbljPmOCkK9JShaTS/viwpFvt3FxiVannif/recV78f369QS1vLPW?blocks=hide
