### ISSUE TITLE
YouTube Regrets Reporter Landing Page (Engineering)

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#6877]
**Engineering** Epic for YouTube Regrets Reporter report share out landing page design.

[View the figma design here](https://www.figma.com/proto/Mp4TDFJIi02sYvxLDTCknF/YouTubeRegretsReporter-Share-Out?page-id=270%3A0&node-id=1093%3A1828&scaling=scale-down-width)

## Links
- [Copy doc](https://docs.google.com/document/d/1pn8CUywtNo2J3rIlgfIKqCyJor1UiiLGqziHzVi_muI/edit?ts=60b6266d#heading=h.6v1ik6cnpxi8)
- [Meeting notes doc](https://docs.google.com/document/d/1SPbtrGhQDs7aSWJt9qx1kqgagGCrouUuDSNUbV2LTrY/edit#)

## Rough Timeline (assuming 2 weeks for dev time)
- June 3: Present 3 rough sketches/wireframes to Brandi (get feedback during the meeting) https://github.com/mozillafoundation/design/issues/850
- June 7: Share final wireframe
- June 9: Present 3 moodboards for the metaphor and look & feel for the landing page https://github.com/MozillaFoundation/Design/issues/870 
- June 16: Present initial rough high-fidelity design mockups to Brandi and Torchbox for feedback [need ticket]
- June 21: Final mockup [need ticket] and prep for dev https://github.com/mozillafoundation/design/issues/868
- June 21: Dev starts [need ticket for design QA]
- July 5: Launch

## Dev notes
This will be a "static" site, in the sense that we don't need a specific Wagtail page for this work. We don't need to worry about adding a header or footer, we just need to add the stuff between those two areas. The header and footer will be inherited from a primary template and the rest of the work can go in the middle. 

By convention, we tend to split out larger "sections" into their own Django template include files to keep the primary template more maintainable. 

There will also be animations (animation specs may change over time as we finalize the design). I'm going to pad each ticket with extra time to account for those types of things, or small styling changes that aren't yet reflected in the design.

## Tickets
- [x] Create a "static" URL for this page, with an empty template (backend) (#6891)
- [x] Create accordion functionality (#6915)
- [x] Create the "read more" functionality (#6917)
- [x] Hero section (#6878) 
- [x] Introduction text (#6879)
- [x] What is a YouTube Regret section (#6880)
- [x] Offensive/Untrue/Bizarre section (#6881) 
- [x] Quote section (#6882)
- [x] Bar chart section with lines (#6883)
- [x] "Our research is powered by real YouTube Users" section 
  - [x] Introduction section (#6884) 
  - [x] Section 01 (#6885)
  - [x] Section 02 (#6886)
  - [x] Section 03 (#6887)
  - [x] Section 04 (#6888)
- [x] Primary text (title, description, lead text) (#6889)
- [x] Download / contributor section(#6890)
- [x] Localization work (#6916)

**Comment by kristinashu** [comment]
Here's the share image from @nancyt1
![YouTube Regrets Report - Share image](https://user-images.githubusercontent.com/1068783/124518331-fa5c7f00-dd9a-11eb-8aa0-d817565cd2a1.jpg). I've added it to the [Assets for dev](https://drive.google.com/drive/folders/1tUDnYe0kXo5jb8i50fzQp4udVDzHj3sf) folder.
