### ISSUE TITLE
[YouTube RegretsReporter] Add link to report

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#6893]
Add a link on https://foundation.mozilla.org/campaigns/regrets-reporter/ to the new report.

### Todo
- [x] Decide on best location
- [x] Work with Brandi on copy
- [x] Mock it up
- [x] Update dev implementation ticket (cc Theo for localisation)

**Comment by kristinashu** [comment]
Comp is here https://redpen.io/mp64e4aef287f4af33 and am asking Brandi for copy feedback.
