### ISSUE TITLE
CMS pages - enhancements

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#704]
Recently I did some design tweaks in the MITI page and I think there are some opportunities for adding some features that allow a bit of more flexibility to the editors. 

- [ ] 1. Modify table to have width equals to 100% so it fits well in the responsive modes. #728 

- [x] 2. Add background colors to make boxes. In case we want to highlight some information and differentiate it from the rest of the text.  #731

- [x] 3. Links in our website (when isolated, not embedded in the middle of a sentence) are all caps and have the →. I was wondering if we could have that option as text format for links?  #731

- [ ] 4. If possible, make the typeface and spaces as we see in the published page. #732

DROPPED (won't fix for now): 
1. ~~Add more space between paragraphs~~

**Comment by xmatthewx** [comment]
Thanks! Let's look for low-to-no-tech solution on this stuff where possible. Ex: create a tips and tricks doc for authors as I mention in 3 below. These are all great and important suggestions, we just have so much else on our plates right now. 

 1. A few default css styles for tables seem reasonable. We could file this as an separate enhancement ticket with help wanted tag. 
 2. Are you suggesting we always add more space between all paragraphs? Sure. Or, enable authors to add more space? We can't address this right now. If they really need it, authors will need to figure it out for their scenario use html creatively. 
 3. Your highlight box looks great. I recommend we start an etherpad or gh-wiki page for authors to share tips, tricks, best practices for stuff like this. We could add a link to it from edit view in CMS. _After_ stuff is well baked for a few months, we can look to address the biggest hiccups and the easiest enhancements.  
 4. If we want this, I recommend we change our default, and then create a class for the specific uppercase+arrow use. But I'm not sure we need this. People can put links in a paragraph or pre to achieve this. 
 5. File this as a separate issue. If mezzanine has an easy way to include site styles in wysiwyg, then great. If not, we'll have to skip this for now.

**Comment by hannahkane** [comment]
Just wanted to clarify that I asked @taisdesouzalessa to file a ticket summarizing some ideas generated from the MITI project. I thought that was an expected outcome of her work there. I don't think either of us was suggesting we do any of this now; we just wanted to capture some learnings from the designer's experience while it's fresh in our minds.

**Comment by alanmoo** [comment]
Pretty much, what Matthew said. There's some good stuff here, I think we need a sprint to figure out how it maps to work that can reasonably be done and what we can highlight for editors.

**Comment by taisdesouzalessa** [comment]
Hey team, thanks for all the input here. I think I caused a confusion here by framing things as questions, which can be seen as requests that should be done soon. Sorry for that! 

Maybe if I had used labels for each issue as "must have", "should have", "could have" would be more useful? Then Matthew and Hannah could take a look and edit the priorities as they see fit? Wonder if you think that would be a better way to do that, let me know so I can make it better next time :)

Love the idea of having a ghpage or Etherpad where all can contribute to tips and tricks in the CMS. Easy and fast to do. I find Etherpad has an easy onboarding for all editors, what do you think, @xmatthewx?

Last question: should I file individual tickets for all those issues then? Or do you wanna pick some that you consider the most important next steps?

**Comment by xmatthewx** [comment]
I think this is all perfect. 

I also think we should pull out a few discreet things as separate tickets and then close this broader discussion. I tried to identify those things in my comment above.

Sorry if my post-vacation quick reply to all my emails and tickets seemed curt. I'm very glad to have this assessment. 😄 😄 😄 😄 😄

**Comment by taisdesouzalessa** [comment]
I created tickets for different issues and made it in an epic as recommended here.  
@xmatthewx @hannahkane feel free to change as you see fit 😊
