### ISSUE TITLE
Design a donate component

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#7112]
Via https://airtable.com/tbljPmOCkK9JShaTS/viwpFvt3FxiVannif/recQwpFU17viEMnkd?blocks=hide

Design a component that staff can easier add in to their content.

Note: this could be broader than just donate. It could be one style of component but could like to either donate, newsletter, a petition etc. 

### Todo
- [ ] Benchmark some examples
- [ ] Mockup a few different options
- [ ] Share with devs and stakeholders for feedback
- [ ] Open implementation ticket

E.g.
https://themarkup.org/ask-the-markup/2021/07/15/are-buy-now-pay-later-retail-loans-a-rip-off

<img width="1170" alt="image" src="https://user-images.githubusercontent.com/1068783/126518600-e08d62b7-b3bb-4c82-9916-e89d993ffac0.png">

<img width="1172" alt="image" src="https://user-images.githubusercontent.com/1068783/126518636-648f65d0-5e93-419e-ba7b-c967fa7c0fef.png">

**Comment by kristinashu** [comment]
This is done as part of the blog and pni updates!
