### ISSUE TITLE
Wagtail demo pages

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#7209]
We need a quick and easy way to show staff and contractors what components we have and how they look.

We should create a few demo pages to show efficiently show off all the possible components and their variations. We should at least create pages for these popular templates:
- [x] Overview page to give high level intro to templates 
- [x] Sketch out page first, where it lives
- [x] Page of all the different components

Maybe these?
- [ ] Publications: update [this demo](https://foundation.mozilla.org/en/docs/how-do-i-wagtail/grimms-fairy-tales-demo/) to include one page with all the components
- [ ] Banner page(s)
- [ ] Blog page(s)

Once the pages are build
- [ ] Add links to https://foundation.mozilla.org/en/docs/how-do-i-wagtail/
- [ ] Add links to some nice real world examples of these templates in use

Bonus of this is that it can also help us efficiently test components to see if a push broken component.

**Comment by beccaklam** [comment]
Making a list of all components here:
- [ ] Paragraph
- [ ] Card grid
- [ ] Image
- [ ] Image text
- [ ] Image text mini
- [ ] Image grid
- [ ] Video
- [ ] Iframe
- [ ] Linkbutton
- [ ] Spacer
- [ ] Quote
- [ ] Pulse listing
- [ ] Profile listing
- [ ] Profile by id
- [ ] Profile directory
- [ ] Recent blog entries
- [ ] Blog set
- [ ] Airtable
- [ ] Typeform

**Comment by beccaklam** [comment]
Redpen with wireframes for template and component pages: https://redpen.io/p/rx483107cd514a81ce
I'm thinking that these pages would live as child pages of "How Do I Wagtail"? But I'm not sure how that works with Article pages or the Component page design that's similar to [this](https://foundation.mozilla.org/en/campaigns/paid-programming/). Let me know what you think! @kristinashu @nancyt1

**Comment by beccaklam** [comment]
Gathering feedback on reiterated wireframes: https://redpen.io/p/rx483107cd514a81ce
Also created content doc for these pages to gather collective wagtail knowledge: https://docs.google.com/document/d/1hY-clLhI0N56v8oWNN5Z1DaYovYK8E2yQsxObVrdK30/edit

**Comment by kristinashu** [comment]
w00t this is done! https://foundation.mozilla.org/en/docs/how-do-i-wagtail/page-types/ & https://foundation.mozilla.org/en/docs/how-do-i-wagtail/streamfield-blocks/
