### ISSUE TITLE
[PNI Website] Gather and edit product images for video apps

### ISSUE THREAD

**Issue by nancyt1** [mozilla/foundation.mozilla.org#7235]
[Product Spreadsheet](https://docs.google.com/spreadsheets/d/1o_Yi7DoSMCb89U9o8OINJBp8H9zkX-f3kGdENekTnHY/edit#gid=1539013424)
[Past Product Logos](https://drive.google.com/drive/u/0/folders/1RBiNJ7xqNtJ_g2M9QqQSWbmg5VcZALSY)
Due Wednesday 8/25

**Todo**
- [x] Assess what we currently have, which ones we need
- [x] Gather images
- [x] Edit and crop them
- [x] Share drive link with Jen when finished

**Comment by nancyt1** [comment]
Added the new logos to the [video app folder](https://drive.google.com/drive/u/0/folders/1b2HEPoXJ7OhQaIOYyTZWacWoC_uxC66m)

**Comment by kristinashu** [comment]
Awesome!
