### ISSUE TITLE
[PNI Website] Update homepage banner & copy

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#7311]
### Todos
- [x] Once creative direction has been established, crop it to fit hero
- [x] Work with Jen to update banner copy
- [x] Update in CMS

**Comment by kristinashu** [comment]
Nancy updated this!
