### ISSUE TITLE
New YouTube RegretsReporter Extension landing page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#7415]
Brandi would like to move away from the campaign story telling style of the current extension page https://foundation.mozilla.org/en/campaigns/regrets-reporter/ to a more product like page, similar to https://www.mozilla.org/en-US/firefox/facebookcontainer/.

We would like to make this work more re-usable for other staff and future projects. For now, it will be a new reusable template but eventually it might be a component that is available throughout the site.

Deadline is mid-end of November. Devs need one sprint to complete this.

I made a very [quick mock-up](https://www.figma.com/proto/A0TYlvLzKxnQLZr3unohQy/YouTube-RegretsReporter---product-page-test?page-id=0%3A1&node-id=2%3A1074&viewport=241%2C48%2C1&scaling=min-zoom&starting-point-node-id=2%3A1074) to help clarify the scope of this project but please don't feel too tied to it.

Some suggested steps but please edit as you see fit!
 

- [x] Meet with Brandi for a project kick-off
- [x] Work with stakeholders on the [copy](https://docs.google.com/document/d/10Vcf7XvSKy7SBZV3AszT32BPBy89hdppBqnbc8NDVMo/edit)
- [x] Mock up page at different screen widths
- [x] Mock up other example use cases of how the template/components could be used
- [x] Meet with devs to talk about feasibility

**Comment by kristinashu** [comment]
I think this is good to close, gonna close it!
