### ISSUE TITLE
Epic: Mozfest Session Slider

### ISSUE THREAD

**Issue by wilhitem** [mozilla/foundation.mozilla.org#7423]
### Design team contact
@sabrinang for feedback

Torchbox designers can be found on slack:
Lindiwe (ux)
Jeth (visual design)

### Final Designs

Figma - https://www.figma.com/file/2knnwWmmqCXuMyF6WPiOuG/MozFest-Additional-Features?node-id=54%3A296

### Details

Help text says "recommend up to 5 items in the slider"
User can move through items using arrow buttons
The component has a heading.

Each item in slider contains:
- Heading *
- author subheading
- Image *
- Video - autoplays on hover (optional)
- rich text copy *
- the card will link to an internal page or external url *

### Implementation Checklist

- [ ] Editor can add a component Heading (required)
- [ ] Editor is advised that 5 items max are added though any number can be added
- [ ] Each item has a Heading (required)
- [ ] Each item has a Sub-heading
- [ ] Each item has a Image (required)
- [ ] Each item has a Video (mp4 or webp) (optional)
- [ ] Each item has a rich text description (required)
- [ ] Each item has a link to an external URL or internal page (required)

**Comment by wilhitem** [comment]
Moving this back to in progress as @stevedya is working to tie together the FE and BE work today
