### ISSUE TITLE
Determine which MozFest blocks to add to the main site

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#8019]
Torchbox and designed and built a few new blocks for the mozfest site including new carousel like sliders and a directory. Design should decide if we want devs to add these new blocks to the main fo'mo site as well.

### Todo
- [x] Determine which blocks are on the mozfest site but not on fo'mo
- [x] Determine which of those blocks would be useful to have on fo/mo
- [x] Determine if those blocks will work on our site by mocking them up in our page types
- [x] Get feedback/input from design & dev
- [ ] Have design -> dev hand-off meeting

**Comment by beccaklam** [comment]
So far after taking a quick look, I think the following would be good additions to fo/mo:
- carousel like slider

**Comment by beccaklam** [comment]
Mocked up the carousel block in this [redpen](https://redpen.io/p/dz260c9693be38fb73) and I think it good to add. Can I get a R+ @kristinashu?

**Comment by kristinashu** [comment]
I left some comments in Redpen. Overall I agree that we should use a lot of the UI styling from the mozfest block. But looking more closely at it in the CMS, it does seem a little confusing to use and specific to events. Can you add some documentation that points out which fields are required vs optional, what they should be called, if a character limit is recommended, image aspect ratios, etc? Also, let's call it a "Slider" rather than a "Carousel" since it think that is more accurate.

**Comment by beccaklam** [comment]
I did some redesigning based on Kristina's comments and after looking more closely at the CMS. Given that we'll need to change the back end anyways, I redesigned the UI a bit as well to make the block flexible for a wider range of uses, namely editorial vs events. Changes can be seen in the [redpen](https://redpen.io/p/dz260c9693be38fb73). I showed options at crit today and we decided to move forward with the Mobile Examples 1 and Desktop Examples 1. 

**The main changes I made were:**
- Reordering the card content to be Image first, followed by Text
- Removing the Subheading Link field
- Adjusting the padding
- Added photo detail text
- Added a counter by the slider arrows
- Added slider arrows to Mobile
- Made the following optional: Slider Title, Slider Item Title, Image, Body, Buttons

I've made notes in the [redpen](https://redpen.io/p/dz260c9693be38fb73) on what pieces should be optional and the following should be included in Body:
- Body Large text
- Bold
- Italic
- Link

@kristinashu Can I get a R+?

**Comment by kristinashu** [comment]
This looks good! Redpen isn't letting me add comments right now but my only feedback is:
- Making the image a required field sounds good to me. It might feel jumpy if one card has an image and then the next one doesn't.
- I'd hold off on video. Might be too much to have it within a slider. We'd also have to limit the file size which could be a big barrier for staff.

Otherwise R+!

**Comment by kristinashu** [comment]
Also a reminder note that this block should be available not only on Articles but on our other page types as well.

**Comment by beccaklam** [comment]
Thank you @kristinashu ! I've implemented the comments you've mentioned. Sorry, could I get one more design pass on the designs? I did a [Mobile Example 2](https://redpen.io/p/dz260c9693be38fb73) where I removed the counter and arrows and only have the bottom ellipses show. This is what the current MozFest block design has and I'm wondering if this solution is cleaner than having the arrows and the counter.

**Comment by kristinashu** [comment]
Yes, I like the simpler mobile version!

**Comment by beccaklam** [comment]
Perfect, okay let's go with Mobile Example 2 then, which is what the current MozFest block default for mobile.

### Design to Dev handoff Checklist:
[Figma File](https://www.figma.com/file/P06Q7hWuILgc9g19AXcP39/Publications-template?node-id=574%3A25973)
[Redpen](https://redpen.io/p/dz260c9693be38fb73)
- [ ] Reorder the card content to be Image first, followed by Text
- [ ] Remove the Subheading Link field
- [ ] Change Image aspect ratio
- [ ] Adjust padding
- [ ] Add photo detail text
- [ ] Add a counter by the slider arrows on desktop
- [ ] Make the following optional: Slider Title, Slider Item Title, Body, Buttons, Image detail text

The following should be included in Body:
- [ ] Body Large text
- [ ] Bold
- [ ] Italic
- [ ] Link

**Comment by beccaklam** [comment]
@kristinashu So for the last checkbox of this ticket says to have a design dev hand-off but Ben mentioned that devs won't be starting on this work until the sprint after next (I think April 11-25?). Can I close this ticket now and make a ticket to have the design to dev meeting the second week of next sprint (perhaps along with the Accordion block?).

**Comment by kristinashu** [comment]
I'm not sure that this block is complex enough to need a full meeting. Perhaps you can just put the info in the above comment into a new dev implementation ticket?

**Comment by beccaklam** [comment]
Sounds good. Implementation ticket created #8473. Closing this ticket!
