### ISSUE TITLE
[Blog] - Landing Page

### ISSUE THREAD

**Issue by danielfmiranda** [mozilla/foundation.mozilla.org#8779]
<img width="303" alt="image" src="https://user-images.githubusercontent.com/18314510/171521555-712d7bfd-3342-4951-962c-b965b287661c.png">

[link to figma designs](https://www.figma.com/file/528nyaJFzvCXAiw2gglwzh/Blog-Improvements?node-id=953%3A33981)

This epic was created to house the work thats going to go into making the blog landing page. 

I believe the order we should do these tickets in are as follow:

- #8780 
- #8782 
- #8783 
- #8685 
- #8688 
- #8785 
- #8781 
- #8784 

Acceptance Criteria:
---

- [ ] Updated template includes Search bar that redirect to search page when the user hits enter
- [x] Users can select 5 posts to feature and they render as designed
- [ ] "Flexible call out" box which has the option to display combination of text, audio player, link button.
- [x] Users can select a "featured video post", that will render as designed
- [x] User can select topics to display in the new "related topics" box.
- [ ] The 8 latest blog posts render, as well as the button to load more results.
- [x] The subscribe to the newsletter box is restyled following the design

**Comment by tbrlpld** [comment]
Moving this to "in progress" since we are working on it.

**Comment by tbrlpld** [comment]
Nobody is working on this. Removing from active sprint.

**Comment by kristinashu** [comment]
@danielfmiranda @nancyt1 it seems like all the tickets within this Epic are completed and the landing page is looking pretty amazing to me! Can you please confirm this is done and if so then close this ticket?

**Comment by nancyt1** [comment]
Landing page looks complete to me!
