### ISSUE TITLE
[Blog] - [Landing] - Style the Landing Page

### ISSUE THREAD

**Issue by danielfmiranda** [mozilla/foundation.mozilla.org#8784]
[Link to Figma Design](https://www.figma.com/file/528nyaJFzvCXAiw2gglwzh/Blog-Improvements?node-id=953%3A33981)

Once all the other components are done, we can now use the template we created in #8780 to house all of them and display them according to the design in figma.

Dev Steps:
---

- [ ] Using tailwind, style the template from #8780 to arrange and display all the new components as designed in figma.
- [ ] Once everything looks good, update "blog_index_page.html" to use the new code from this template
- [ ] Delete template from #8780  

Acceptance Criteria:
---
The page should show the following:

- [ ] Page Title
- [ ] Description
- [ ] Global Search #8778 
- [ ] Featured Posts Section #8782 
- [ ] Featured Callout Box #8783 
- [ ] Feature Video Post Section #8685 
- [ ] Latest Blog Post Section #8785 
- [ ] Popular Topic Callout Section #8688 
- [ ] Newsletter Callout Box #8781

**Comment by danielfmiranda** [comment]
Moving this one to blocked until I merge in #8992

**Comment by cdanfon** [comment]
Hey @danielfmiranda Is this issue still blocked? Thanks!

**Comment by danielfmiranda** [comment]
Closed with #9185

**Comment by tbrlpld** [comment]
@danielfmiranda Has this been QA'd on staging? Looks from the updates your moved it straight from "review" to "closed".

**Comment by danielfmiranda** [comment]
Hi @tbrlpld! Apologies, there was some confusion as the PR was not letting the design team click "Approve" on the PR, however, they have commented on the PR #9185 that they tested the updates on staging and approve.
