### ISSUE TITLE
[Epic] [YouTube RegretsReporter] Design

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#9075]
Launch date Sept 20

## Links
- [Folder in drive](https://drive.google.com/drive/folders/1e-cJr1Jp1DQ8uTsQhJdYfyjLFJkNkGG4?usp=sharing)
- [Initial meeting with Becca](https://docs.google.com/document/d/1L3FamyNzeyGBbjYpNW1-8od9PsVFzFAnqy45Kvk2lIA/edit#)  
- [Wider project timeline and deliverables](https://docs.google.com/spreadsheets/d/1S9bifU0274UgeLF7duIaaAtOJEQ8n_6LgeS-PYrLOKA/edit#gid=0)
- Broader kick-off meeting on findings and policy approach: [notes](https://docs.google.com/document/d/1r5D7yW_kBh5IeK1QJlOYy8zQjQ4rLdwj79l4eGHbNhY/edit#heading=h.opi7tndzcgrg), [slides](https://docs.google.com/presentation/d/1LU-1wsiQC9PmhGzaGXY1xO-BNKBQYu8SokfBfBEi-7g/edit#slide=id.g11692a30c0b_0_38) and [recording](https://mozilla.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=183a2db1-6524-4696-aeec-aed000fce621) 
- [Draft copy of full report](https://docs.google.com/document/d/1jBgaNJ_oyOeb-4RtiocHRBeqMm0vqWswIskssFdZsBo/edit#heading=h.llccrxlsqjnh)
- [Draft copy for landing page](https://docs.google.com/document/d/1-QU-Yv17WjAa788tNFmAxWbTJT7NGY2snY5qPSEGlWk/edit#)
- Slack channel # 2022-youtube-production
- [Figjam](https://www.figma.com/file/xQGKDpi1RZdoQ6UoNYtWEQ/YouTube-RegretsReporter-User-Control-Jam?node-id=0%3A1)
- [Figma mockups](https://www.figma.com/file/XtEAabujYbKaP5mLnCtvVS/YouTube-User-Control-Report-Landing-Page?node-id=0%3A1)
- [Design/Dev meeting notes](https://docs.google.com/document/d/1FJ4uUtj8w9eq84CvKP-AftFcXuMGx7dQKrtuKhoT7aE/edit?usp=sharing)

URLs
- /youtube/user-controls
- [tbd]/user-controls/report
- /campaign/user-controls

### Discovery
- [x] Write design brief https://github.com/MozillaFoundation/Design/issues/1075
- [x] Onboard to the project https://github.com/mozillafoundation/design/issues/1068 
- [x] Create overview roadmap ([Design roadmap](https://docs.google.com/spreadsheets/d/1YZUl4vcQnJ8QYntH1SwPtffu71fnDY87olIex65tkF0/edit#gid=1982140116) & [project timeline](https://docs.google.com/spreadsheets/d/1S9bifU0274UgeLF7duIaaAtOJEQ8n_6LgeS-PYrLOKA/edit#gid=0))

### Explore
- [x] Brainstorm on visualizations https://github.com/MozillaFoundation/Design/issues/1076
- [x] Brainstorm content IA for landing page https://github.com/MozillaFoundation/Design/issues/1077
- [x] Plan _"Crafting the narrative – building a compelling narrative around the research that will resonate with different audiences through our written materials, comms, marketing, and design."_ with marketing team
- [x] Illustration work https://github.com/MozillaFoundation/Design/issues/1081
- [x] Animation work?
- [x] Data visualization in Datawrapper [need ticket]
- [x] Design landing page https://github.com/mozilla/foundation.mozilla.org/issues/9222

### Implement
- [x] Landing page (either article of custom)  [need tickets]
- [x] Full report in Publications page type [need ticket]
- [x] Full report as a PDF [need ticket]
- [ ] Marketing assets [need ticket]
- [x] Small dev bug fixes [need ticket]
- [x] Update hub [need ticket]

cc @sabrinang @beccaklam @nancyt1

**Comment by kristinashu** [comment]
I've tentatively updated the timelines to see what it would look like if we did the illustrations in-house: [Design roadmap](https://docs.google.com/spreadsheets/d/1YZUl4vcQnJ8QYntH1SwPtffu71fnDY87olIex65tkF0/edit#gid=1982140116) & [Project timeline](https://docs.google.com/spreadsheets/d/1S9bifU0274UgeLF7duIaaAtOJEQ8n_6LgeS-PYrLOKA/edit#gid=0).

Comparing it to [last year's timeline](https://docs.google.com/spreadsheets/d/1Thz0_tJ57br1l1blkJpFEHuLnaCuOHL7C5_fAq_azjE/edit#gid=0), it seems to me like we have about twice as much time (and we aren't designing and building a custom site). But let's discuss later this week as we see how other work is going and if our scope expectations are aligned with the stakeholders.

**Comment by kristinashu** [comment]
Thank you @sabrinang @beccaklam for going over the timeline! 

I've added links above from this mornings meeting about the findings, definitely insightful and worth watching later.
