### ISSUE TITLE
[YouTube RegretsReporter] Design Timeline for Dev Handoff

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#9217]
### Description:
Design needs to be finalized for devs to start working on it August 22nd (mid-sprint). Design should reflect the recommendation pairs over time.

**Applicable links:**
- [Jesse's recommendation pairs pdf](https://drive.google.com/drive/folders/19sPAJnFlaUU-OAhQ9CJ3uM478LMq-rrB?usp=sharing)
- [YouTube User Control Study: Landing Page draft copy](https://docs.google.com/document/d/1-QU-Yv17WjAa788tNFmAxWbTJT7NGY2snY5qPSEGlWk/edit?usp=sharing)

**Tasks**
- [x] First draft of designs (have a simple/backup/low dev/low interaction, blue sky versions, also mobile/tablet)
- [x] Share with design team for feedback, revise
- [x] Share with design, stakeholders and torchbox devs for review by ~EOD Thursday, Aug 18~ Aug 23 and also request final content for design
- [x] Revise based on feedback from everyone (second draft) (Share by Tues, Aug 23 EOD)
- [x] Share with design, developers and stakeholders again for final revisions (Tues, Aug 23 EOD)
- [x] Last revision based on feedback (Wed Aug 24, share by EOD)
- [x] Timeline design is finalized for Thurs, Aug 25

Acceptance Criteria
**Timeline designed for**
- [x] Desktop
- [x] Mobile
- [x] Tablet
- [x] Implementation notes and examples are included in Figma file

**Comment by beccaklam** [comment]
The beginnings of a first draft have been started as reflected in this [redpen](https://redpen.io/p/bc0790c8ec7927ff81). I still have to work on annotating and maybe building out a rough after effects file to show what I'm thinking for a more dev involved version. Still need to work on mobile and tablet versions.

**Comment by beccaklam** [comment]
Designs have been completed for:
- Dev light version
- Dev 'more-involved' version
- Mobile
- Tablet
Will show designs at the project meeting tomorrow to get feedback from stakeholders and hopefully get clarity on finalizing content and illustration directions.

**Comment by beccaklam** [comment]
This was completed yesterday after some back and forth between design and dev regarding a simplification of the timeline. The animation for this timeline will be based on this [benchmark](https://theraelettes.com/) but some simplifications may need to be made given the deadline. The final figma file can be found [here](https://www.figma.com/file/XtEAabujYbKaP5mLnCtvVS/YouTube-User-Control-Report-Landing-Page?node-id=0%3A1).
