### ISSUE TITLE
[YouTube RegretsReport] Support petition page set up

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#9335]
We will need the petition ready before launch on Sept 20.

URL needs to be https://foundation.mozilla.org/campaigns/youtube-user-controls/ since this is what the landing page links to.

Christian is working on the ask.

@anilkanji and I will help Christian in setting up the petition page.

Note I will be on PTO Sept 15 & 16

### Todo
- [ ] Get copy
- [ ] Get number in Salesforce
- [ ] Set up page in CMS
- [ ] Add OG image
- [ ] Test
