### ISSUE TITLE
[PNI] About page copy updates

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#9483]
### Todo
- [ ] Get copy from Jen
- [ ] Check formatting 
- [ ] Update dev ticket https://github.com/mozilla/foundation.mozilla.org/issues/9527 and let them know it's unblocked 
- [ ] Théo to localize the changes in DE, ES, FR, PT

**Comment by kristinashu** [comment]
Thank you for the edit @TheoChevalier!

**Comment by kristinashu** [comment]
Closing this since there won't be any updates this year
