### ISSUE TITLE
Design new Space block for Mozfest site refresh

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#9504]
Request via @marcwalsh @bheasman (cc @mtdenton) 

See [Miro board](https://miro.com/app/board/uXjVOqdUb5g=/?moveToWidget=3458764533403232677&cot=14) for wireframe of the block.

### Todo
- [x] Design the new block in Figma
- [x] Determine a flexible name for the block (name is already set my DFL block)
- [x] Compare to similar existing blocks, chat with devs to determine if this should be a new block or an adapted version of an existing one 
- [x] Share with stakeholder, design team, and devs for feedback
- [ ] Hand-off to devs

**Comment by marcwalsh** [comment]
Hi @kristinashu - thanks for this! I think the block that is being made for the DFL works great, and might also make it easier and quicker to implement if it's already being worked on.

**Comment by kristinashu** [comment]
@cdanfon has added the optional button link to https://github.com/mozilla/foundation.mozilla.org/issues/9400#issuecomment-1286718242

The optional diving lines still need a ticket. @mtdenton @cdanfon should I open one for that? Would love to be able to close this ticket today as it's the last day of sprint.

**Comment by mtdenton** [comment]
@kristinashu sounds good, obviously the DFL ticket is a blocker here but we can at least signify the work.

**Comment by bheasman** [comment]
@mtdenton - the DFL ticket should be wrapped up this week, so the dependency should be resolved pretty soon.
