### ISSUE TITLE
[PNI] Add ids or classes to new elements for tracking purposes

### ISSUE THREAD

**Issue by nancyt1** [mozilla/foundation.mozilla.org#9609]
**Homepage Editorial Content**
- [x] Add id to featured article div
- [x] Add id for related section associated with featured article

**Related Articles**
Add id or class to related or popular article blocks around the site. I wanted to be able to tell if clicks are coming from related blocks, these don't have to be unique to each one but some pages do have 2 places where it appears so an ID distinguishing which section (like top or bottom) would be helpful.
- [x] Article post page for top and bottom sections
- [x] Article index page
- [x] Product pages
- [x] Category pages (not implemented yet I don't think)

**Related Products Block**
- [x] Add id or class to "Related Products" section on product pages

**Newsletter Signup**
Not sure if this is possible but would be great to have!
- [x] Add id to newsletter signup in the product grid
- [x] Add id to newsletter signup at the end of article index and post pages

**Comment by tbrlpld** [comment]
Left two optional questions.

**Comment by danielfmiranda** [comment]
Hi @nancyt1! This is now on staging and ready to be tested if you would like to take a look. Thanks!

**Comment by danielfmiranda** [comment]
This has been tested together with design and they confirm that the classes/ google tag manager is working as expected. Closing!
