### ISSUE TITLE
Upgrade Wagtail to 3.0

### ISSUE THREAD

**Issue by tbrlpld** [mozilla/foundation.mozilla.org#9674]
## Description

Goal of this ticket is to upgrade Wagtail to version 3.0. This ticket is a follow up to the Spike #8534. 

Before we can upgrade Wagtail, we need to address the following tickets:

- [x] Upgrade `wagtail-localize-git` to 0.13 (#9675)
- [x] Upgrade `wagtail-inventory` to 1.6 (#9676)
- [x] Remove Airtable integration (#9147)

During upgrade we need to address the following:

- Changes to module paths.
    - Basically all imports to core wagtail modules need to be updated.
    - There is a management command provided to update all import paths.
- Removal of special-purpose field panel types
    - All special field panels (like `RichTextFieldPanel` , `StreamFieldPanel`, etc.) can be replaced with the basic `FieldPanel`. The detection now happens automatically.
- Use `use_json_field` argument for `StreamField`
    - All uses of `StreamField`should be updated to include the argument `use_json_field=True`.
- Running the migrations might take a while, because of some restructuring internally. We will see this on staging, since staging has quite similar data as production.

See also: https://docs.wagtail.org/en/stable/releases/3.0.html

## Dev notes

- [x] Create upgrade branch from main
- [x] Check your project’s console output for any deprecation warnings, and fix them where necessary `python -Wa manage.py check`
- [x] Check the new version’s release notes 
- [x] Check the compatible Django / Python versions [table](https://docs.wagtail.io/en/stable/releases/upgrading.html#compatible-django-python-versions), for any dependencies that need upgrading first;
- [x] Upgrade supporting requirements (Python, Django) if necessary
- [x] Upgrade Wagtail
- [x] Make new migration (might result in none). 
- [x] Migrate database changes (locally)
- [x] Implement needed changes from upgrade considerations (see above)
- [x] Perform testing
	- [x] Run test suites 
	- [ ] Smoke test site / testing journeys (manually on the site)
	- [ ] Smoke test admin (Click around in the admin to see if anything is broken)
- [ ] Check for new deprecations `python -Wa manage.py check` and fix if necessary

## Acceptance criteria 

- [ ] Wagtail is upgraded to version 3.0
- [ ] ticket for Wagtail 4.1 upgrade is created

**Comment by kevinhowbrook** [comment]
- [ ] Upgrade `wagtail-localize-git` to 0.13 (#9675) PR https://github.com/mozilla/foundation.mozilla.org/pull/9894
- [ ] Upgrade `wagtail-inventory` to 1.6 (#9676) PR https://github.com/mozilla/foundation.mozilla.org/pull/9895
- [ ] Remove Airtable integration (#9147) PR https://github.com/mozilla/foundation.mozilla.org/pull/9896

**Comment by kevinhowbrook** [comment]
This is causing a problem https://github.com/MozillaFoundation/wagtail-footnotes/blob/master/setup.cfg#L25

Pretty sure we need to update the fork so I'll refork and try it

**Comment by kevinhowbrook** [comment]
Progress with this is going ok but slow.
At the moment I'm trying to figure out these failing tests https://github.com/mozilla/foundation.mozilla.org/actions/runs/3857119974/jobs/6574150905#step:13:79

So far I think it's something with initializing the form in tests or the fact the search fields are from a mixin. Perhaps both

**Comment by kevinhowbrook** [comment]
Looks like get_form_for_model has been updated https://github.com/wagtail/wagtail/blob/v3.0/wagtail/admin/tests/test_edit_handlers.py#L61-L62

**Comment by kevinhowbrook** [comment]
Tests are passing and I've updated everything - the only thing I can see as outstanding atm is https://github.com/MozillaFoundation/wagtail-footnotes/pull/2

**Comment by kevinhowbrook** [comment]
The PR #9904 is ready to merge for stage testing, BUT we are going to wait for some comms on this first.

**Comment by kevinhowbrook** [comment]
W4 issue created here https://github.com/mozilla/foundation.mozilla.org/issues/10004

**Comment by cdanfon** [comment]
Next steps is for @kevinhowbrook to start a deployment plan doc and share it with the team

**Comment by kevinhowbrook** [comment]
PR is balanced and ready to merge.

Link to upgrade plan https://docs.google.com/document/d/1zDSnRVGn3exeYUv_CBkDvL1-dv4Koms9KGBLyox2Bqs/edit

**Comment by cdanfon** [comment]
Hey @kevinhowbrook thanks for this, can you please merge to main?
