### ISSUE TITLE
Update our social links

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#9919]
We link to our social channels in a few different places across our sites and they should be updated to better reflect our most active channels.

### Todo
- [x] Audit all the key places we show our socials (footer on fo'mo/pni/mozfest, subscribe to our newsletter block on /blog, etc) 
- [x] Decide where it makes sense to update them
- [x] Add Tiktok & LinkedIn
- [x] Remove Github 
- [x] Create svg icons
- [x] Make sure all icons and hover states are consistent 
- [x] Reduce file size of svg
- [x] Open dev ticket to implement 

Note we do now want to add Mastodon yet as we haven't established it yet, also don't want to add Spotify

**Comment by nancyt1** [comment]
List of places we show socials (WIP):
1. Fo'mo Footer
2. PNI Footer
3. Mozfest Footer
4. What you can do [page](https://foundation.mozilla.org/en/what-you-can-do/)
5. Newsletter on Blog [homepage](https://foundation.mozilla.org/en/blog/)
6.

**Comment by mmmavis** [comment]
# WIP, will move this line when I finish updating this comment

@nancyt1 

I found a few more places that include the social links (in addition to your list above):

1. After users signed up for a petition. e.g., https://foundation.mozilla.org/en/campaigns/youtube-user-controls/ <img width="380" alt="image" src="https://user-images.githubusercontent.com/2896608/212772623-d3f3edc5-223f-4c86-95bd-991f8de3700d.png">

2. After voted on PNI's product page  e.g., https://foundation.mozilla.org/en/privacynotincluded/threema/ 
<img width="768" alt="image" src="https://user-images.githubusercontent.com/2896608/212772930-ac89ca2b-1dac-4b54-849e-c67a7c90bdc1.png">

3. Article page. e.g., https://foundation.mozilla.org/en/docs/how-do-i-wagtail/grimms-fairy-tales-demo/foreward/

3. PNI Article page. e.g, https://foundation.mozilla.org/en/privacynotincluded/articles/alexa-help-me-which-smart-speaker-has-the-best-privacy/

4. Blog page. e.g., https://foundation.mozilla.org/en/blog/meet-julie-ricard-building-a-better-social-media-platform/

(... to be added)

**Comment by mmmavis** [comment]
@nancyt1 

Donate modal has a screen with social links. I'm not sure if we get to control what shows up there though. We will need to investigate. 
<img src="https://user-images.githubusercontent.com/102978346/212058752-13321731-1f5e-4cf9-9ef8-cdec5419f844.png">

**Comment by kristinashu** [comment]
My original intention for this ticket was more about were we link out to our social channels and not necessarily about our share asks, although updating those does make sense but should perhaps be a different ticket? Note about share links: I think adding LinkedIn makes sense and we should keep Facebook but I would hold off on adding Tiktok to those (but let me check with Audrey first to confirm). I don't think the FRU one needs to be updated.

**Comment by kristinashu** [comment]
Thank you Nancy!

Audrey suggested to add Linkedin and Tiktok to the our "Follow us" instances. It was just the "Share on social" instances that I haven't talked to her about. 

@nancyt1 could you also please open another ticket to add tracking events to the icons? It would be nice to know if people are actually clicking on them, which ones and where they're clicking on them.

**Comment by nancyt1** [comment]
Opened [dev ticket](https://github.com/mozilla/foundation.mozilla.org/issues/9985)
